-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    2011a.41 Production Release
--  HLS Date:       Thu Apr  7 20:28:55 PDT 2011
-- 
--  Generated by:   ss@DESKTOP-UB05SU4
--  Generated date: Tue Apr 09 16:47:26 2019
-- ----------------------------------------------------------------------

-- 
-- ------------------------------------------------------------------
--  Design Unit:    Adding_core
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.std_logic_arith.ALL;
LIBRARY mgc_hls;
USE mgc_hls.funcs.ALL;
USE work.adding_mux_pkg.ALL;


ENTITY Adding_core IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    A_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    B_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    C_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    D_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    E_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    Temp_rsc_mgc_out_stdreg_d : OUT STD_LOGIC_VECTOR (63 DOWNTO 0)
  );
END Adding_core;

ARCHITECTURE v11 OF Adding_core IS
  -- Default Constants

BEGIN
  -- Default Constant Signal Assignments

  core : PROCESS
    -- Interconnect Declarations
    VARIABLE A_1_sva : STD_LOGIC_VECTOR (7 DOWNTO 0);
    VARIABLE B_1_sva : STD_LOGIC_VECTOR (7 DOWNTO 0);
    VARIABLE C_1_sva : STD_LOGIC_VECTOR (7 DOWNTO 0);
    VARIABLE D_1_sva : STD_LOGIC_VECTOR (7 DOWNTO 0);
    VARIABLE E_1_sva : STD_LOGIC_VECTOR (7 DOWNTO 0);
    VARIABLE in_i_2_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_1_sva_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_2_sva_1 : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE out_1_mul_1_cse_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
    VARIABLE Temp2_2_sva : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_3_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_2_sva_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_3_sva_1 : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_3_sva : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_4_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_3_sva_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_4_sva_1 : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_4_sva : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_5_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_4_sva_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_5_sva_1 : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_5_sva : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_6_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_5_sva_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_6_sva_1 : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_6_sva : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_7_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_6_sva_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_7_sva_1 : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_7_sva : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_8_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_7_sva_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_8_sva_1 : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_8_sva : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_9_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_8_sva_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_9_sva_1 : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_9_sva : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_10_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_9_sva_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_10_sva_1 : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_10_sva : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_11_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_10_sva_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_11_sva_1 : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_11_sva : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_1_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE Temp2_11_sva_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
    VARIABLE in_i_1_sva_1 : STD_LOGIC_VECTOR (2 DOWNTO 0);

  BEGIN
    main : LOOP
      -- C-Step 0 of Loop 'main'
      WAIT UNTIL clk'EVENT AND ( clk = '1' );
      EXIT main WHEN ( rst = '1' );
      -- C-Step 1 of Loop 'main'
      A_1_sva := A_rsc_mgc_in_wire_d;
      B_1_sva := B_rsc_mgc_in_wire_d;
      C_1_sva := C_rsc_mgc_in_wire_d;
      D_1_sva := D_rsc_mgc_in_wire_d;
      E_1_sva := E_rsc_mgc_in_wire_d;
      in_i_2_sva := STD_LOGIC_VECTOR'("000");
      out_1_in : LOOP
        -- C-Step 0 of Loop 'out_1_in'
        WAIT UNTIL clk'EVENT AND ( clk = '1' );
        EXIT main WHEN ( rst = '1' );
        -- C-Step 1 of Loop 'out_1_in'
        Temp2_1_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(Temp2_1_sva_1) +
            CONV_UNSIGNED(UNSIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(A_1_sva),
            9) + CONV_UNSIGNED(UNSIGNED(B_1_sva(7 DOWNTO 1)), 9), 9)) & TO_STDLOGICVECTOR(B_1_sva(0))),
            11) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(C_1_sva), 9) + CONV_UNSIGNED(UNSIGNED(D_1_sva),
            9), 11), 11)), 2, 9)), 64), 64));
        in_i_2_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(in_i_2_sva) + CONV_UNSIGNED(CONV_UNSIGNED('1',
            1), 3), 3));
        EXIT out_1_in WHEN ( (readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1')
            & (in_i_2_sva_1(2 DOWNTO 1))) + CONV_SIGNED(CONV_UNSIGNED('1', 1), 3),
            3)), 2)) = '0' );
        in_i_2_sva := in_i_2_sva_1;
      END LOOP out_1_in;

      WAIT UNTIL clk'EVENT AND ( clk = '1' );
      EXIT main WHEN ( rst = '1' );
      -- C-Step 2 of Loop 'main'
      out_1_mul_1_cse_sva := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(E_1_sva)
          * UNSIGNED(E_1_sva)), 16));
      WAIT UNTIL clk'EVENT AND ( clk = '1' );
      EXIT main WHEN ( rst = '1' );
      -- C-Step 3 of Loop 'main'
      Temp2_2_sva := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(Temp2_1_sva_1)
          * UNSIGNED(out_1_mul_1_cse_sva)), 64));
      in_i_3_sva := STD_LOGIC_VECTOR'("000");
      out_2_in : LOOP
        -- C-Step 0 of Loop 'out_2_in'
        WAIT UNTIL clk'EVENT AND ( clk = '1' );
        EXIT main WHEN ( rst = '1' );
        -- C-Step 1 of Loop 'out_2_in'
        Temp2_2_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(Temp2_2_sva) + CONV_UNSIGNED(UNSIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(A_1_sva),
            9) + CONV_UNSIGNED(UNSIGNED(B_1_sva(7 DOWNTO 1)), 9), 9)) & TO_STDLOGICVECTOR(B_1_sva(0))),
            11) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(C_1_sva), 9) + CONV_UNSIGNED(UNSIGNED(D_1_sva),
            9), 11), 11)), 2, 9)), 64), 64));
        in_i_3_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(in_i_3_sva) + CONV_UNSIGNED(CONV_UNSIGNED('1',
            1), 3), 3));
        EXIT out_2_in WHEN ( (readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1')
            & (in_i_3_sva_1(2 DOWNTO 1))) + CONV_SIGNED(CONV_UNSIGNED('1', 1), 3),
            3)), 2)) = '0' );
        in_i_3_sva := in_i_3_sva_1;
        Temp2_2_sva := Temp2_2_sva_1;
      END LOOP out_2_in;

      WAIT UNTIL clk'EVENT AND ( clk = '1' );
      EXIT main WHEN ( rst = '1' );
      -- C-Step 4 of Loop 'main'
      Temp2_3_sva := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(Temp2_2_sva_1)
          * UNSIGNED(out_1_mul_1_cse_sva)), 64));
      in_i_4_sva := STD_LOGIC_VECTOR'("000");
      out_3_in : LOOP
        -- C-Step 0 of Loop 'out_3_in'
        WAIT UNTIL clk'EVENT AND ( clk = '1' );
        EXIT main WHEN ( rst = '1' );
        -- C-Step 1 of Loop 'out_3_in'
        Temp2_3_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(Temp2_3_sva) + CONV_UNSIGNED(UNSIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(A_1_sva),
            9) + CONV_UNSIGNED(UNSIGNED(B_1_sva(7 DOWNTO 1)), 9), 9)) & TO_STDLOGICVECTOR(B_1_sva(0))),
            11) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(C_1_sva), 9) + CONV_UNSIGNED(UNSIGNED(D_1_sva),
            9), 11), 11)), 2, 9)), 64), 64));
        in_i_4_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(in_i_4_sva) + CONV_UNSIGNED(CONV_UNSIGNED('1',
            1), 3), 3));
        EXIT out_3_in WHEN ( (readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1')
            & (in_i_4_sva_1(2 DOWNTO 1))) + CONV_SIGNED(CONV_UNSIGNED('1', 1), 3),
            3)), 2)) = '0' );
        in_i_4_sva := in_i_4_sva_1;
        Temp2_3_sva := Temp2_3_sva_1;
      END LOOP out_3_in;

      WAIT UNTIL clk'EVENT AND ( clk = '1' );
      EXIT main WHEN ( rst = '1' );
      -- C-Step 5 of Loop 'main'
      Temp2_4_sva := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(Temp2_3_sva_1)
          * UNSIGNED(out_1_mul_1_cse_sva)), 64));
      in_i_5_sva := STD_LOGIC_VECTOR'("000");
      out_4_in : LOOP
        -- C-Step 0 of Loop 'out_4_in'
        WAIT UNTIL clk'EVENT AND ( clk = '1' );
        EXIT main WHEN ( rst = '1' );
        -- C-Step 1 of Loop 'out_4_in'
        Temp2_4_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(Temp2_4_sva) + CONV_UNSIGNED(UNSIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(A_1_sva),
            9) + CONV_UNSIGNED(UNSIGNED(B_1_sva(7 DOWNTO 1)), 9), 9)) & TO_STDLOGICVECTOR(B_1_sva(0))),
            11) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(C_1_sva), 9) + CONV_UNSIGNED(UNSIGNED(D_1_sva),
            9), 11), 11)), 2, 9)), 64), 64));
        in_i_5_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(in_i_5_sva) + CONV_UNSIGNED(CONV_UNSIGNED('1',
            1), 3), 3));
        EXIT out_4_in WHEN ( (readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1')
            & (in_i_5_sva_1(2 DOWNTO 1))) + CONV_SIGNED(CONV_UNSIGNED('1', 1), 3),
            3)), 2)) = '0' );
        in_i_5_sva := in_i_5_sva_1;
        Temp2_4_sva := Temp2_4_sva_1;
      END LOOP out_4_in;

      WAIT UNTIL clk'EVENT AND ( clk = '1' );
      EXIT main WHEN ( rst = '1' );
      -- C-Step 6 of Loop 'main'
      Temp2_5_sva := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(Temp2_4_sva_1)
          * UNSIGNED(out_1_mul_1_cse_sva)), 64));
      in_i_6_sva := STD_LOGIC_VECTOR'("000");
      out_5_in : LOOP
        -- C-Step 0 of Loop 'out_5_in'
        WAIT UNTIL clk'EVENT AND ( clk = '1' );
        EXIT main WHEN ( rst = '1' );
        -- C-Step 1 of Loop 'out_5_in'
        Temp2_5_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(Temp2_5_sva) + CONV_UNSIGNED(UNSIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(A_1_sva),
            9) + CONV_UNSIGNED(UNSIGNED(B_1_sva(7 DOWNTO 1)), 9), 9)) & TO_STDLOGICVECTOR(B_1_sva(0))),
            11) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(C_1_sva), 9) + CONV_UNSIGNED(UNSIGNED(D_1_sva),
            9), 11), 11)), 2, 9)), 64), 64));
        in_i_6_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(in_i_6_sva) + CONV_UNSIGNED(CONV_UNSIGNED('1',
            1), 3), 3));
        EXIT out_5_in WHEN ( (readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1')
            & (in_i_6_sva_1(2 DOWNTO 1))) + CONV_SIGNED(CONV_UNSIGNED('1', 1), 3),
            3)), 2)) = '0' );
        in_i_6_sva := in_i_6_sva_1;
        Temp2_5_sva := Temp2_5_sva_1;
      END LOOP out_5_in;

      WAIT UNTIL clk'EVENT AND ( clk = '1' );
      EXIT main WHEN ( rst = '1' );
      -- C-Step 7 of Loop 'main'
      Temp2_6_sva := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(Temp2_5_sva_1)
          * UNSIGNED(out_1_mul_1_cse_sva)), 64));
      in_i_7_sva := STD_LOGIC_VECTOR'("000");
      out_6_in : LOOP
        -- C-Step 0 of Loop 'out_6_in'
        WAIT UNTIL clk'EVENT AND ( clk = '1' );
        EXIT main WHEN ( rst = '1' );
        -- C-Step 1 of Loop 'out_6_in'
        Temp2_6_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(Temp2_6_sva) + CONV_UNSIGNED(UNSIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(A_1_sva),
            9) + CONV_UNSIGNED(UNSIGNED(B_1_sva(7 DOWNTO 1)), 9), 9)) & TO_STDLOGICVECTOR(B_1_sva(0))),
            11) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(C_1_sva), 9) + CONV_UNSIGNED(UNSIGNED(D_1_sva),
            9), 11), 11)), 2, 9)), 64), 64));
        in_i_7_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(in_i_7_sva) + CONV_UNSIGNED(CONV_UNSIGNED('1',
            1), 3), 3));
        EXIT out_6_in WHEN ( (readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1')
            & (in_i_7_sva_1(2 DOWNTO 1))) + CONV_SIGNED(CONV_UNSIGNED('1', 1), 3),
            3)), 2)) = '0' );
        in_i_7_sva := in_i_7_sva_1;
        Temp2_6_sva := Temp2_6_sva_1;
      END LOOP out_6_in;

      WAIT UNTIL clk'EVENT AND ( clk = '1' );
      EXIT main WHEN ( rst = '1' );
      -- C-Step 8 of Loop 'main'
      Temp2_7_sva := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(Temp2_6_sva_1)
          * UNSIGNED(out_1_mul_1_cse_sva)), 64));
      in_i_8_sva := STD_LOGIC_VECTOR'("000");
      out_7_in : LOOP
        -- C-Step 0 of Loop 'out_7_in'
        WAIT UNTIL clk'EVENT AND ( clk = '1' );
        EXIT main WHEN ( rst = '1' );
        -- C-Step 1 of Loop 'out_7_in'
        Temp2_7_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(Temp2_7_sva) + CONV_UNSIGNED(UNSIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(A_1_sva),
            9) + CONV_UNSIGNED(UNSIGNED(B_1_sva(7 DOWNTO 1)), 9), 9)) & TO_STDLOGICVECTOR(B_1_sva(0))),
            11) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(C_1_sva), 9) + CONV_UNSIGNED(UNSIGNED(D_1_sva),
            9), 11), 11)), 2, 9)), 64), 64));
        in_i_8_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(in_i_8_sva) + CONV_UNSIGNED(CONV_UNSIGNED('1',
            1), 3), 3));
        EXIT out_7_in WHEN ( (readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1')
            & (in_i_8_sva_1(2 DOWNTO 1))) + CONV_SIGNED(CONV_UNSIGNED('1', 1), 3),
            3)), 2)) = '0' );
        in_i_8_sva := in_i_8_sva_1;
        Temp2_7_sva := Temp2_7_sva_1;
      END LOOP out_7_in;

      WAIT UNTIL clk'EVENT AND ( clk = '1' );
      EXIT main WHEN ( rst = '1' );
      -- C-Step 9 of Loop 'main'
      Temp2_8_sva := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(Temp2_7_sva_1)
          * UNSIGNED(out_1_mul_1_cse_sva)), 64));
      in_i_9_sva := STD_LOGIC_VECTOR'("000");
      out_8_in : LOOP
        -- C-Step 0 of Loop 'out_8_in'
        WAIT UNTIL clk'EVENT AND ( clk = '1' );
        EXIT main WHEN ( rst = '1' );
        -- C-Step 1 of Loop 'out_8_in'
        Temp2_8_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(Temp2_8_sva) + CONV_UNSIGNED(UNSIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(A_1_sva),
            9) + CONV_UNSIGNED(UNSIGNED(B_1_sva(7 DOWNTO 1)), 9), 9)) & TO_STDLOGICVECTOR(B_1_sva(0))),
            11) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(C_1_sva), 9) + CONV_UNSIGNED(UNSIGNED(D_1_sva),
            9), 11), 11)), 2, 9)), 64), 64));
        in_i_9_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(in_i_9_sva) + CONV_UNSIGNED(CONV_UNSIGNED('1',
            1), 3), 3));
        EXIT out_8_in WHEN ( (readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1')
            & (in_i_9_sva_1(2 DOWNTO 1))) + CONV_SIGNED(CONV_UNSIGNED('1', 1), 3),
            3)), 2)) = '0' );
        in_i_9_sva := in_i_9_sva_1;
        Temp2_8_sva := Temp2_8_sva_1;
      END LOOP out_8_in;

      WAIT UNTIL clk'EVENT AND ( clk = '1' );
      EXIT main WHEN ( rst = '1' );
      -- C-Step 10 of Loop 'main'
      Temp2_9_sva := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(Temp2_8_sva_1)
          * UNSIGNED(out_1_mul_1_cse_sva)), 64));
      in_i_10_sva := STD_LOGIC_VECTOR'("000");
      out_9_in : LOOP
        -- C-Step 0 of Loop 'out_9_in'
        WAIT UNTIL clk'EVENT AND ( clk = '1' );
        EXIT main WHEN ( rst = '1' );
        -- C-Step 1 of Loop 'out_9_in'
        Temp2_9_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(Temp2_9_sva) + CONV_UNSIGNED(UNSIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(A_1_sva),
            9) + CONV_UNSIGNED(UNSIGNED(B_1_sva(7 DOWNTO 1)), 9), 9)) & TO_STDLOGICVECTOR(B_1_sva(0))),
            11) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(C_1_sva), 9) + CONV_UNSIGNED(UNSIGNED(D_1_sva),
            9), 11), 11)), 2, 9)), 64), 64));
        in_i_10_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(in_i_10_sva) + CONV_UNSIGNED(CONV_UNSIGNED('1',
            1), 3), 3));
        EXIT out_9_in WHEN ( (readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1')
            & (in_i_10_sva_1(2 DOWNTO 1))) + CONV_SIGNED(CONV_UNSIGNED('1', 1), 3),
            3)), 2)) = '0' );
        in_i_10_sva := in_i_10_sva_1;
        Temp2_9_sva := Temp2_9_sva_1;
      END LOOP out_9_in;

      WAIT UNTIL clk'EVENT AND ( clk = '1' );
      EXIT main WHEN ( rst = '1' );
      -- C-Step 11 of Loop 'main'
      Temp2_10_sva := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(Temp2_9_sva_1)
          * UNSIGNED(out_1_mul_1_cse_sva)), 64));
      in_i_11_sva := STD_LOGIC_VECTOR'("000");
      out_10_in : LOOP
        -- C-Step 0 of Loop 'out_10_in'
        WAIT UNTIL clk'EVENT AND ( clk = '1' );
        EXIT main WHEN ( rst = '1' );
        -- C-Step 1 of Loop 'out_10_in'
        Temp2_10_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(Temp2_10_sva) +
            CONV_UNSIGNED(UNSIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(A_1_sva),
            9) + CONV_UNSIGNED(UNSIGNED(B_1_sva(7 DOWNTO 1)), 9), 9)) & TO_STDLOGICVECTOR(B_1_sva(0))),
            11) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(C_1_sva), 9) + CONV_UNSIGNED(UNSIGNED(D_1_sva),
            9), 11), 11)), 2, 9)), 64), 64));
        in_i_11_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(in_i_11_sva) + CONV_UNSIGNED(CONV_UNSIGNED('1',
            1), 3), 3));
        EXIT out_10_in WHEN ( (readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1')
            & (in_i_11_sva_1(2 DOWNTO 1))) + CONV_SIGNED(CONV_UNSIGNED('1', 1), 3),
            3)), 2)) = '0' );
        in_i_11_sva := in_i_11_sva_1;
        Temp2_10_sva := Temp2_10_sva_1;
      END LOOP out_10_in;

      in_i_1_sva := STD_LOGIC_VECTOR'("000");
      WAIT UNTIL clk'EVENT AND ( clk = '1' );
      EXIT main WHEN ( rst = '1' );
      -- C-Step 12 of Loop 'main'
      Temp2_11_sva := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(Temp2_10_sva_1)
          * UNSIGNED(out_1_mul_1_cse_sva)), 64));
      out_11_in : LOOP
        -- C-Step 0 of Loop 'out_11_in'
        WAIT UNTIL clk'EVENT AND ( clk = '1' );
        EXIT main WHEN ( rst = '1' );
        -- C-Step 1 of Loop 'out_11_in'
        Temp2_11_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(Temp2_11_sva) +
            CONV_UNSIGNED(UNSIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(A_1_sva),
            9) + CONV_UNSIGNED(UNSIGNED(B_1_sva(7 DOWNTO 1)), 9), 9)) & TO_STDLOGICVECTOR(B_1_sva(0))),
            11) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(C_1_sva), 9) + CONV_UNSIGNED(UNSIGNED(D_1_sva),
            9), 11), 11)), 2, 9)), 64), 64));
        in_i_1_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(in_i_1_sva) + CONV_UNSIGNED(CONV_UNSIGNED('1',
            1), 3), 3));
        EXIT out_11_in WHEN ( (readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1')
            & (in_i_1_sva_1(2 DOWNTO 1))) + CONV_SIGNED(CONV_UNSIGNED('1', 1), 3),
            3)), 2)) = '0' );
        in_i_1_sva := in_i_1_sva_1;
        Temp2_11_sva := Temp2_11_sva_1;
      END LOOP out_11_in;

      WAIT UNTIL clk'EVENT AND ( clk = '1' );
      EXIT main WHEN ( rst = '1' );
      -- C-Step 13 of Loop 'main'
      Temp_rsc_mgc_out_stdreg_d <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(Temp2_11_sva_1)
          * UNSIGNED(out_1_mul_1_cse_sva)), 64));
      WAIT UNTIL clk'EVENT AND ( clk = '1' );
      EXIT main WHEN ( rst = '1' );
      -- C-Step 14 of Loop 'main'
    END LOOP main;

    in_i_1_sva_1 := STD_LOGIC_VECTOR'("000");
    Temp2_11_sva_1 := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_1_sva := STD_LOGIC_VECTOR'("000");
    Temp2_11_sva := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_11_sva_1 := STD_LOGIC_VECTOR'("000");
    Temp2_10_sva_1 := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_11_sva := STD_LOGIC_VECTOR'("000");
    Temp2_10_sva := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_10_sva_1 := STD_LOGIC_VECTOR'("000");
    Temp2_9_sva_1 := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_10_sva := STD_LOGIC_VECTOR'("000");
    Temp2_9_sva := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_9_sva_1 := STD_LOGIC_VECTOR'("000");
    Temp2_8_sva_1 := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_9_sva := STD_LOGIC_VECTOR'("000");
    Temp2_8_sva := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_8_sva_1 := STD_LOGIC_VECTOR'("000");
    Temp2_7_sva_1 := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_8_sva := STD_LOGIC_VECTOR'("000");
    Temp2_7_sva := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_7_sva_1 := STD_LOGIC_VECTOR'("000");
    Temp2_6_sva_1 := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_7_sva := STD_LOGIC_VECTOR'("000");
    Temp2_6_sva := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_6_sva_1 := STD_LOGIC_VECTOR'("000");
    Temp2_5_sva_1 := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_6_sva := STD_LOGIC_VECTOR'("000");
    Temp2_5_sva := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_5_sva_1 := STD_LOGIC_VECTOR'("000");
    Temp2_4_sva_1 := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_5_sva := STD_LOGIC_VECTOR'("000");
    Temp2_4_sva := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_4_sva_1 := STD_LOGIC_VECTOR'("000");
    Temp2_3_sva_1 := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_4_sva := STD_LOGIC_VECTOR'("000");
    Temp2_3_sva := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_3_sva_1 := STD_LOGIC_VECTOR'("000");
    Temp2_2_sva_1 := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_3_sva := STD_LOGIC_VECTOR'("000");
    Temp2_2_sva := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    out_1_mul_1_cse_sva := STD_LOGIC_VECTOR'("0000000000000000");
    in_i_2_sva_1 := STD_LOGIC_VECTOR'("000");
    Temp2_1_sva_1 := STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
    in_i_2_sva := STD_LOGIC_VECTOR'("000");
    E_1_sva := STD_LOGIC_VECTOR'("00000000");
    D_1_sva := STD_LOGIC_VECTOR'("00000000");
    C_1_sva := STD_LOGIC_VECTOR'("00000000");
    B_1_sva := STD_LOGIC_VECTOR'("00000000");
    A_1_sva := STD_LOGIC_VECTOR'("00000000");
    Temp_rsc_mgc_out_stdreg_d <= STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
  END PROCESS core;

END v11;

-- ------------------------------------------------------------------
--  Design Unit:    Adding
--  Generated from file(s):
--    2) $PROJECT_HOME/ESL.c
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.std_logic_arith.ALL;
LIBRARY mgc_hls;
USE mgc_hls.funcs.ALL;
USE work.adding_mux_pkg.ALL;


ENTITY Adding IS
  PORT(
    A_rsc_z : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    B_rsc_z : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    C_rsc_z : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    D_rsc_z : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    E_rsc_z : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    Temp_rsc_z : OUT STD_LOGIC_VECTOR (63 DOWNTO 0);
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC
  );
END Adding;

ARCHITECTURE v11 OF Adding IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL A_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL B_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL C_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL D_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL E_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL Temp_rsc_mgc_out_stdreg_d : STD_LOGIC_VECTOR (63 DOWNTO 0);

  SIGNAL A_rsc_mgc_in_wire_d_1 : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL A_rsc_mgc_in_wire_z : STD_LOGIC_VECTOR (7 DOWNTO 0);

  SIGNAL B_rsc_mgc_in_wire_d_1 : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL B_rsc_mgc_in_wire_z : STD_LOGIC_VECTOR (7 DOWNTO 0);

  SIGNAL C_rsc_mgc_in_wire_d_1 : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL C_rsc_mgc_in_wire_z : STD_LOGIC_VECTOR (7 DOWNTO 0);

  SIGNAL D_rsc_mgc_in_wire_d_1 : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL D_rsc_mgc_in_wire_z : STD_LOGIC_VECTOR (7 DOWNTO 0);

  SIGNAL E_rsc_mgc_in_wire_d_1 : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL E_rsc_mgc_in_wire_z : STD_LOGIC_VECTOR (7 DOWNTO 0);

  SIGNAL Temp_rsc_mgc_out_stdreg_d_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
  SIGNAL Temp_rsc_mgc_out_stdreg_z : STD_LOGIC_VECTOR (63 DOWNTO 0);

  COMPONENT Adding_core
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      A_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
      B_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
      C_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
      D_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
      E_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
      Temp_rsc_mgc_out_stdreg_d : OUT STD_LOGIC_VECTOR (63 DOWNTO 0)
    );
  END COMPONENT;
  SIGNAL Adding_core_inst_A_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL Adding_core_inst_B_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL Adding_core_inst_C_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL Adding_core_inst_D_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL Adding_core_inst_E_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL Adding_core_inst_Temp_rsc_mgc_out_stdreg_d : STD_LOGIC_VECTOR (63 DOWNTO
      0);

BEGIN
  -- Default Constant Signal Assignments

  A_rsc_mgc_in_wire : mgc_hls.mgc_ioport_comps.mgc_in_wire
    GENERIC MAP(
      rscid => 1,
      width => 8
      )
    PORT MAP(
      d => A_rsc_mgc_in_wire_d_1,
      z => A_rsc_mgc_in_wire_z
    );
  A_rsc_mgc_in_wire_d <= A_rsc_mgc_in_wire_d_1;
  A_rsc_mgc_in_wire_z <= A_rsc_z;

  B_rsc_mgc_in_wire : mgc_hls.mgc_ioport_comps.mgc_in_wire
    GENERIC MAP(
      rscid => 2,
      width => 8
      )
    PORT MAP(
      d => B_rsc_mgc_in_wire_d_1,
      z => B_rsc_mgc_in_wire_z
    );
  B_rsc_mgc_in_wire_d <= B_rsc_mgc_in_wire_d_1;
  B_rsc_mgc_in_wire_z <= B_rsc_z;

  C_rsc_mgc_in_wire : mgc_hls.mgc_ioport_comps.mgc_in_wire
    GENERIC MAP(
      rscid => 3,
      width => 8
      )
    PORT MAP(
      d => C_rsc_mgc_in_wire_d_1,
      z => C_rsc_mgc_in_wire_z
    );
  C_rsc_mgc_in_wire_d <= C_rsc_mgc_in_wire_d_1;
  C_rsc_mgc_in_wire_z <= C_rsc_z;

  D_rsc_mgc_in_wire : mgc_hls.mgc_ioport_comps.mgc_in_wire
    GENERIC MAP(
      rscid => 4,
      width => 8
      )
    PORT MAP(
      d => D_rsc_mgc_in_wire_d_1,
      z => D_rsc_mgc_in_wire_z
    );
  D_rsc_mgc_in_wire_d <= D_rsc_mgc_in_wire_d_1;
  D_rsc_mgc_in_wire_z <= D_rsc_z;

  E_rsc_mgc_in_wire : mgc_hls.mgc_ioport_comps.mgc_in_wire
    GENERIC MAP(
      rscid => 5,
      width => 8
      )
    PORT MAP(
      d => E_rsc_mgc_in_wire_d_1,
      z => E_rsc_mgc_in_wire_z
    );
  E_rsc_mgc_in_wire_d <= E_rsc_mgc_in_wire_d_1;
  E_rsc_mgc_in_wire_z <= E_rsc_z;

  Temp_rsc_mgc_out_stdreg : mgc_hls.mgc_ioport_comps.mgc_out_stdreg
    GENERIC MAP(
      rscid => 6,
      width => 64
      )
    PORT MAP(
      d => Temp_rsc_mgc_out_stdreg_d_1,
      z => Temp_rsc_mgc_out_stdreg_z
    );
  Temp_rsc_mgc_out_stdreg_d_1 <= Temp_rsc_mgc_out_stdreg_d;
  Temp_rsc_z <= Temp_rsc_mgc_out_stdreg_z;

  Adding_core_inst : adding_core
    PORT MAP(
      clk => clk,
      rst => rst,
      A_rsc_mgc_in_wire_d => Adding_core_inst_A_rsc_mgc_in_wire_d,
      B_rsc_mgc_in_wire_d => Adding_core_inst_B_rsc_mgc_in_wire_d,
      C_rsc_mgc_in_wire_d => Adding_core_inst_C_rsc_mgc_in_wire_d,
      D_rsc_mgc_in_wire_d => Adding_core_inst_D_rsc_mgc_in_wire_d,
      E_rsc_mgc_in_wire_d => Adding_core_inst_E_rsc_mgc_in_wire_d,
      Temp_rsc_mgc_out_stdreg_d => Adding_core_inst_Temp_rsc_mgc_out_stdreg_d
    );
  Adding_core_inst_A_rsc_mgc_in_wire_d <= A_rsc_mgc_in_wire_d;
  Adding_core_inst_B_rsc_mgc_in_wire_d <= B_rsc_mgc_in_wire_d;
  Adding_core_inst_C_rsc_mgc_in_wire_d <= C_rsc_mgc_in_wire_d;
  Adding_core_inst_D_rsc_mgc_in_wire_d <= D_rsc_mgc_in_wire_d;
  Adding_core_inst_E_rsc_mgc_in_wire_d <= E_rsc_mgc_in_wire_d;
  Temp_rsc_mgc_out_stdreg_d <= Adding_core_inst_Temp_rsc_mgc_out_stdreg_d;

END v11;



