directive set /Adding/Adding:core/core/Temp2#10.sva REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#11.sva REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#2.sva REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#3.sva REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#4.sva REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#5.sva REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#6.sva REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#7.sva REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#8.sva REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#9.sva REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#10.sva#1 REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#11.sva#1 REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#2.sva#1 REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#3.sva#1 REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#4.sva#1 REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#5.sva#1 REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#6.sva#1 REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#7.sva#1 REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#8.sva#1 REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/Temp2#9.sva#1 REGISTER_NAME reg#1
directive set /Adding/Adding:core/core/in:i#1.sva REGISTER_NAME in.reg
directive set /Adding/Adding:core/core/in:i#10.sva REGISTER_NAME in.reg
directive set /Adding/Adding:core/core/in:i#11.sva REGISTER_NAME in.reg
directive set /Adding/Adding:core/core/in:i#2.sva REGISTER_NAME in.reg
directive set /Adding/Adding:core/core/in:i#3.sva REGISTER_NAME in.reg
directive set /Adding/Adding:core/core/in:i#4.sva REGISTER_NAME in.reg
directive set /Adding/Adding:core/core/in:i#5.sva REGISTER_NAME in.reg
directive set /Adding/Adding:core/core/in:i#6.sva REGISTER_NAME in.reg
directive set /Adding/Adding:core/core/in:i#7.sva REGISTER_NAME in.reg
directive set /Adding/Adding:core/core/in:i#8.sva REGISTER_NAME in.reg
directive set /Adding/Adding:core/core/in:i#9.sva REGISTER_NAME in.reg
