directive set /Adding/Adding:core/Adding:core:conc/out-1:in:acc#5 RESOURCE_NAME mgc_Altera-Cyclone-II-6_beh_psr.mgc_add(64,0,9,0,64)
directive set /Adding/Adding:core/Adding:core:conc/out-2:in:acc#5 RESOURCE_NAME mgc_Altera-Cyclone-II-6_beh_psr.mgc_add(64,0,9,0,64)
directive set /Adding/Adding:core/Adding:core:conc/out-1:mul#1 RESOURCE_NAME mgc_Altera-Cyclone-II-6_beh_psr.mgc_mul(16,0,64,0,64)
directive set /Adding/Adding:core/Adding:core:conc/out-1:mul RESOURCE_NAME mgc_Altera-Cyclone-II-6_beh_psr.mgc_mul(16,0,64,0,64)
directive set /Adding/Adding:core/Adding:core:conc/out-2:mul RESOURCE_NAME mgc_Altera-Cyclone-II-6_beh_psr.mgc_mul(16,0,64,0,64)
