-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    2011a.41 Production Release
--  HLS Date:       Thu Apr  7 20:28:55 PDT 2011
-- 
--  Generated by:   ss@DESKTOP-UB05SU4
--  Generated date: Tue Apr 09 16:47:36 2019
-- ----------------------------------------------------------------------

-- 
-- ------------------------------------------------------------------
--  Design Unit:    Adding_core_fsm
--  FSM Module
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.std_logic_arith.ALL;
LIBRARY mgc_hls;
USE mgc_hls.funcs.ALL;
USE work.adding_mux_pkg.ALL;


ENTITY Adding_core_fsm IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    fsm_output : OUT STD_LOGIC_VECTOR (24 DOWNTO 0);
    st_out_1_in_tr0 : IN STD_LOGIC;
    st_out_2_in_tr0 : IN STD_LOGIC;
    st_out_3_in_tr0 : IN STD_LOGIC;
    st_out_4_in_tr0 : IN STD_LOGIC;
    st_out_5_in_tr0 : IN STD_LOGIC;
    st_out_6_in_tr0 : IN STD_LOGIC;
    st_out_7_in_tr0 : IN STD_LOGIC;
    st_out_8_in_tr0 : IN STD_LOGIC;
    st_out_9_in_tr0 : IN STD_LOGIC;
    st_out_10_in_tr0 : IN STD_LOGIC;
    st_out_11_in_tr0 : IN STD_LOGIC
  );
END Adding_core_fsm;

ARCHITECTURE v11 OF Adding_core_fsm IS
  -- Default Constants

  -- FSM State Type Declaration for Adding_core_fsm_1
  TYPE Adding_core_fsm_1_ST IS (st_main, st_out_1_in, st_main_1, st_main_2, st_out_2_in,
      st_main_3, st_out_3_in, st_main_4, st_out_4_in, st_main_5, st_out_5_in, st_main_6,
      st_out_6_in, st_main_7, st_out_7_in, st_main_8, st_out_8_in, st_main_9, st_out_9_in,
      st_main_10, st_out_10_in, st_main_11, st_out_11_in, st_main_12, st_main_13);

  SIGNAL state_var : Adding_core_fsm_1_ST;
  SIGNAL state_var_NS : Adding_core_fsm_1_ST;

BEGIN
  -- Default Constant Signal Assignments

  Adding_core_fsm_1 : PROCESS (st_out_1_in_tr0, st_out_2_in_tr0, st_out_3_in_tr0,
      st_out_4_in_tr0, st_out_5_in_tr0, st_out_6_in_tr0, st_out_7_in_tr0, st_out_8_in_tr0,
      st_out_9_in_tr0, st_out_10_in_tr0, st_out_11_in_tr0, state_var)
  BEGIN
    CASE state_var IS
      WHEN st_main =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000000000000000001");
        state_var_NS <= st_out_1_in;
      WHEN st_out_1_in =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000000000000000010");
        IF ( st_out_1_in_tr0 = '1' ) THEN
          state_var_NS <= st_main_1;
        ELSE
          state_var_NS <= st_out_1_in;
        END IF;
      WHEN st_main_1 =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000000000000000100");
        state_var_NS <= st_main_2;
      WHEN st_main_2 =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000000000000001000");
        state_var_NS <= st_out_2_in;
      WHEN st_out_2_in =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000000000000010000");
        IF ( st_out_2_in_tr0 = '1' ) THEN
          state_var_NS <= st_main_3;
        ELSE
          state_var_NS <= st_out_2_in;
        END IF;
      WHEN st_main_3 =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000000000000100000");
        state_var_NS <= st_out_3_in;
      WHEN st_out_3_in =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000000000001000000");
        IF ( st_out_3_in_tr0 = '1' ) THEN
          state_var_NS <= st_main_4;
        ELSE
          state_var_NS <= st_out_3_in;
        END IF;
      WHEN st_main_4 =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000000000010000000");
        state_var_NS <= st_out_4_in;
      WHEN st_out_4_in =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000000000100000000");
        IF ( st_out_4_in_tr0 = '1' ) THEN
          state_var_NS <= st_main_5;
        ELSE
          state_var_NS <= st_out_4_in;
        END IF;
      WHEN st_main_5 =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000000001000000000");
        state_var_NS <= st_out_5_in;
      WHEN st_out_5_in =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000000010000000000");
        IF ( st_out_5_in_tr0 = '1' ) THEN
          state_var_NS <= st_main_6;
        ELSE
          state_var_NS <= st_out_5_in;
        END IF;
      WHEN st_main_6 =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000000100000000000");
        state_var_NS <= st_out_6_in;
      WHEN st_out_6_in =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000001000000000000");
        IF ( st_out_6_in_tr0 = '1' ) THEN
          state_var_NS <= st_main_7;
        ELSE
          state_var_NS <= st_out_6_in;
        END IF;
      WHEN st_main_7 =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000010000000000000");
        state_var_NS <= st_out_7_in;
      WHEN st_out_7_in =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000000100000000000000");
        IF ( st_out_7_in_tr0 = '1' ) THEN
          state_var_NS <= st_main_8;
        ELSE
          state_var_NS <= st_out_7_in;
        END IF;
      WHEN st_main_8 =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000001000000000000000");
        state_var_NS <= st_out_8_in;
      WHEN st_out_8_in =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000010000000000000000");
        IF ( st_out_8_in_tr0 = '1' ) THEN
          state_var_NS <= st_main_9;
        ELSE
          state_var_NS <= st_out_8_in;
        END IF;
      WHEN st_main_9 =>
        fsm_output <= STD_LOGIC_VECTOR'("0000000100000000000000000");
        state_var_NS <= st_out_9_in;
      WHEN st_out_9_in =>
        fsm_output <= STD_LOGIC_VECTOR'("0000001000000000000000000");
        IF ( st_out_9_in_tr0 = '1' ) THEN
          state_var_NS <= st_main_10;
        ELSE
          state_var_NS <= st_out_9_in;
        END IF;
      WHEN st_main_10 =>
        fsm_output <= STD_LOGIC_VECTOR'("0000010000000000000000000");
        state_var_NS <= st_out_10_in;
      WHEN st_out_10_in =>
        fsm_output <= STD_LOGIC_VECTOR'("0000100000000000000000000");
        IF ( st_out_10_in_tr0 = '1' ) THEN
          state_var_NS <= st_main_11;
        ELSE
          state_var_NS <= st_out_10_in;
        END IF;
      WHEN st_main_11 =>
        fsm_output <= STD_LOGIC_VECTOR'("0001000000000000000000000");
        state_var_NS <= st_out_11_in;
      WHEN st_out_11_in =>
        fsm_output <= STD_LOGIC_VECTOR'("0010000000000000000000000");
        IF ( st_out_11_in_tr0 = '1' ) THEN
          state_var_NS <= st_main_12;
        ELSE
          state_var_NS <= st_out_11_in;
        END IF;
      WHEN st_main_12 =>
        fsm_output <= STD_LOGIC_VECTOR'("0100000000000000000000000");
        state_var_NS <= st_main_13;
      WHEN st_main_13 =>
        fsm_output <= STD_LOGIC_VECTOR'("1000000000000000000000000");
        state_var_NS <= st_main;
      WHEN OTHERS =>
        fsm_output <= "0000000000000000000000000";
        state_var_NS <= st_main;
    END CASE;
  END PROCESS Adding_core_fsm_1;

  Adding_core_fsm_1_REG : PROCESS (clk)
  BEGIN
    IF clk'event AND ( clk = '1' ) THEN
      IF ( rst = '1' ) THEN
        state_var <= st_main;
      ELSE
        state_var <= state_var_NS;
      END IF;
    END IF;
  END PROCESS Adding_core_fsm_1_REG;

END v11;

-- ------------------------------------------------------------------
--  Design Unit:    Adding_core
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.std_logic_arith.ALL;
LIBRARY mgc_hls;
USE mgc_hls.funcs.ALL;
USE work.adding_mux_pkg.ALL;


ENTITY Adding_core IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    A_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    B_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    C_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    D_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    E_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    Temp_rsc_mgc_out_stdreg_d : OUT STD_LOGIC_VECTOR (63 DOWNTO 0)
  );
END Adding_core;

ARCHITECTURE v11 OF Adding_core IS
  -- Default Constants

  -- Output Reader Declarations
  SIGNAL Temp_rsc_mgc_out_stdreg_d_drv : STD_LOGIC_VECTOR (63 DOWNTO 0);

  -- Interconnect Declarations
  SIGNAL fsm_output : STD_LOGIC_VECTOR (24 DOWNTO 0);
  SIGNAL or_dcpl_172 : STD_LOGIC;
  SIGNAL or_dcpl_175 : STD_LOGIC;
  SIGNAL A_1_sva : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL B_1_sva : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL C_1_sva : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL D_1_sva : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL E_1_sva : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL Temp2_1_sva_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
  SIGNAL out_1_mul_1_cse_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL reg_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
  SIGNAL in_reg : STD_LOGIC_VECTOR (2 DOWNTO 0);
  SIGNAL out_1_in_acc_12 : STD_LOGIC_VECTOR (2 DOWNTO 0);
  SIGNAL or_104_cse : STD_LOGIC;
  SIGNAL z_out : STD_LOGIC_VECTOR (63 DOWNTO 0);
  SIGNAL or_tmp_1 : STD_LOGIC;
  SIGNAL z_out_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
  SIGNAL in_i_2_sva_1 : STD_LOGIC_VECTOR (2 DOWNTO 0);

  SIGNAL mux_10_nl : STD_LOGIC_VECTOR (63 DOWNTO 0);
  SIGNAL mux_9_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL mux1h_6_nl : STD_LOGIC_VECTOR (63 DOWNTO 0);
  COMPONENT Adding_core_fsm
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      fsm_output : OUT STD_LOGIC_VECTOR (24 DOWNTO 0);
      st_out_1_in_tr0 : IN STD_LOGIC;
      st_out_2_in_tr0 : IN STD_LOGIC;
      st_out_3_in_tr0 : IN STD_LOGIC;
      st_out_4_in_tr0 : IN STD_LOGIC;
      st_out_5_in_tr0 : IN STD_LOGIC;
      st_out_6_in_tr0 : IN STD_LOGIC;
      st_out_7_in_tr0 : IN STD_LOGIC;
      st_out_8_in_tr0 : IN STD_LOGIC;
      st_out_9_in_tr0 : IN STD_LOGIC;
      st_out_10_in_tr0 : IN STD_LOGIC;
      st_out_11_in_tr0 : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL Adding_core_fsm_inst_fsm_output : STD_LOGIC_VECTOR (24 DOWNTO 0);
  SIGNAL Adding_core_fsm_inst_st_out_1_in_tr0 : STD_LOGIC;
  SIGNAL Adding_core_fsm_inst_st_out_2_in_tr0 : STD_LOGIC;
  SIGNAL Adding_core_fsm_inst_st_out_3_in_tr0 : STD_LOGIC;
  SIGNAL Adding_core_fsm_inst_st_out_4_in_tr0 : STD_LOGIC;
  SIGNAL Adding_core_fsm_inst_st_out_5_in_tr0 : STD_LOGIC;
  SIGNAL Adding_core_fsm_inst_st_out_6_in_tr0 : STD_LOGIC;
  SIGNAL Adding_core_fsm_inst_st_out_7_in_tr0 : STD_LOGIC;
  SIGNAL Adding_core_fsm_inst_st_out_8_in_tr0 : STD_LOGIC;
  SIGNAL Adding_core_fsm_inst_st_out_9_in_tr0 : STD_LOGIC;
  SIGNAL Adding_core_fsm_inst_st_out_10_in_tr0 : STD_LOGIC;
  SIGNAL Adding_core_fsm_inst_st_out_11_in_tr0 : STD_LOGIC;

BEGIN
  -- Default Constant Signal Assignments

  -- Output Reader Assignments
  Temp_rsc_mgc_out_stdreg_d <= Temp_rsc_mgc_out_stdreg_d_drv;

  Adding_core_fsm_inst : adding_core_fsm
    PORT MAP(
      clk => clk,
      rst => rst,
      fsm_output => Adding_core_fsm_inst_fsm_output,
      st_out_1_in_tr0 => Adding_core_fsm_inst_st_out_1_in_tr0,
      st_out_2_in_tr0 => Adding_core_fsm_inst_st_out_2_in_tr0,
      st_out_3_in_tr0 => Adding_core_fsm_inst_st_out_3_in_tr0,
      st_out_4_in_tr0 => Adding_core_fsm_inst_st_out_4_in_tr0,
      st_out_5_in_tr0 => Adding_core_fsm_inst_st_out_5_in_tr0,
      st_out_6_in_tr0 => Adding_core_fsm_inst_st_out_6_in_tr0,
      st_out_7_in_tr0 => Adding_core_fsm_inst_st_out_7_in_tr0,
      st_out_8_in_tr0 => Adding_core_fsm_inst_st_out_8_in_tr0,
      st_out_9_in_tr0 => Adding_core_fsm_inst_st_out_9_in_tr0,
      st_out_10_in_tr0 => Adding_core_fsm_inst_st_out_10_in_tr0,
      st_out_11_in_tr0 => Adding_core_fsm_inst_st_out_11_in_tr0
    );
  fsm_output <= Adding_core_fsm_inst_fsm_output;
  Adding_core_fsm_inst_st_out_1_in_tr0 <= NOT (out_1_in_acc_12(2));
  Adding_core_fsm_inst_st_out_2_in_tr0 <= NOT (out_1_in_acc_12(2));
  Adding_core_fsm_inst_st_out_3_in_tr0 <= NOT (out_1_in_acc_12(2));
  Adding_core_fsm_inst_st_out_4_in_tr0 <= NOT (out_1_in_acc_12(2));
  Adding_core_fsm_inst_st_out_5_in_tr0 <= NOT (out_1_in_acc_12(2));
  Adding_core_fsm_inst_st_out_6_in_tr0 <= NOT (out_1_in_acc_12(2));
  Adding_core_fsm_inst_st_out_7_in_tr0 <= NOT (out_1_in_acc_12(2));
  Adding_core_fsm_inst_st_out_8_in_tr0 <= NOT (out_1_in_acc_12(2));
  Adding_core_fsm_inst_st_out_9_in_tr0 <= NOT (out_1_in_acc_12(2));
  Adding_core_fsm_inst_st_out_10_in_tr0 <= NOT (out_1_in_acc_12(2));
  Adding_core_fsm_inst_st_out_11_in_tr0 <= NOT (out_1_in_acc_12(2));

  or_104_cse <= (fsm_output(21)) OR (fsm_output(19)) OR (fsm_output(17)) OR (fsm_output(15))
      OR (fsm_output(13)) OR (fsm_output(11)) OR (fsm_output(9)) OR (fsm_output(7))
      OR (fsm_output(5)) OR (fsm_output(2)) OR (fsm_output(20)) OR (fsm_output(18))
      OR (fsm_output(16)) OR (fsm_output(14)) OR (fsm_output(12)) OR (fsm_output(10))
      OR (fsm_output(8)) OR (fsm_output(6)) OR (fsm_output(4)) OR (fsm_output(22))
      OR (fsm_output(1)) OR (fsm_output(3));
  in_i_2_sva_1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(in_reg) + CONV_UNSIGNED(CONV_UNSIGNED('1',
      1), 3), 3));
  out_1_in_acc_12 <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1') &
      (in_i_2_sva_1(2 DOWNTO 1))) + CONV_SIGNED(CONV_UNSIGNED('1', 1), 3), 3));
  or_dcpl_172 <= (fsm_output(14)) OR (fsm_output(12));
  or_dcpl_175 <= (fsm_output(20)) OR (fsm_output(18)) OR (fsm_output(16));
  or_tmp_1 <= (fsm_output(5)) OR (fsm_output(7)) OR (fsm_output(9)) OR (fsm_output(11))
      OR (fsm_output(13)) OR (fsm_output(15)) OR (fsm_output(17)) OR (fsm_output(19))
      OR (fsm_output(21)) OR (fsm_output(23));
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        Temp_rsc_mgc_out_stdreg_d_drv <= STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
        A_1_sva <= STD_LOGIC_VECTOR'("00000000");
        B_1_sva <= STD_LOGIC_VECTOR'("00000000");
        C_1_sva <= STD_LOGIC_VECTOR'("00000000");
        D_1_sva <= STD_LOGIC_VECTOR'("00000000");
        Temp2_1_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
        E_1_sva <= STD_LOGIC_VECTOR'("00000000");
        in_reg <= STD_LOGIC_VECTOR'("000");
        out_1_mul_1_cse_sva <= STD_LOGIC_VECTOR'("0000000000000000");
        reg_1 <= STD_LOGIC_VECTOR'("0000000000000000000000000000000000000000000000000000000000000000");
      ELSE
        Temp_rsc_mgc_out_stdreg_d_drv <= MUX_v_64_2_2(Temp_rsc_mgc_out_stdreg_d_drv
            & z_out_1, fsm_output(23));
        A_1_sva <= MUX_v_8_2_2(A_rsc_mgc_in_wire_d & A_1_sva, or_104_cse);
        B_1_sva <= MUX_v_8_2_2(B_rsc_mgc_in_wire_d & B_1_sva, or_104_cse);
        C_1_sva <= MUX_v_8_2_2(C_rsc_mgc_in_wire_d & C_1_sva, or_104_cse);
        D_1_sva <= MUX_v_8_2_2(D_rsc_mgc_in_wire_d & D_1_sva, or_104_cse);
        Temp2_1_sva_1 <= MUX_v_64_2_2(Temp2_1_sva_1 & z_out, fsm_output(1));
        E_1_sva <= MUX_v_8_2_2(E_1_sva & E_rsc_mgc_in_wire_d, fsm_output(0));
        in_reg <= in_i_2_sva_1 AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(or_dcpl_175
            OR or_dcpl_172 OR (fsm_output(10)) OR (fsm_output(8)) OR (fsm_output(6))
            OR (fsm_output(4)) OR (fsm_output(22)) OR (fsm_output(1)), 1),3));
        out_1_mul_1_cse_sva <= MUX_v_16_2_2(out_1_mul_1_cse_sva & (z_out_1(15 DOWNTO
            0)), fsm_output(2));
        reg_1 <= MUX_v_64_2_2(z_out_1 & z_out, or_dcpl_175 OR or_dcpl_172 OR (fsm_output(10))
            OR (fsm_output(8)) OR (fsm_output(6)) OR (fsm_output(4)) OR (fsm_output(22)));
      END IF;
    END IF;
  END PROCESS;
  mux_10_nl <= MUX_v_64_2_2(Temp2_1_sva_1 & reg_1, (fsm_output(4)) OR (fsm_output(6))
      OR (fsm_output(8)) OR (fsm_output(10)) OR (fsm_output(12)) OR (fsm_output(14))
      OR (fsm_output(16)) OR (fsm_output(18)) OR (fsm_output(20)) OR (fsm_output(22)));
  z_out <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(mux_10_nl) + CONV_UNSIGNED(UNSIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(A_1_sva),
      9) + CONV_UNSIGNED(UNSIGNED(B_1_sva(7 DOWNTO 1)), 9), 9)) & TO_STDLOGICVECTOR(B_1_sva(0))),
      11) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(C_1_sva), 9) + CONV_UNSIGNED(UNSIGNED(D_1_sva),
      9), 11), 11)), 2, 9)), 64), 64));
  mux_9_nl <= MUX_v_16_2_2((STD_LOGIC_VECTOR'("00000000") & E_1_sva) & out_1_mul_1_cse_sva,
      (fsm_output(3)) OR or_tmp_1);
  mux1h_6_nl <= MUX1HOT_v_64_3_2((STD_LOGIC_VECTOR'("00000000000000000000000000000000000000000000000000000000")
      & E_1_sva) & Temp2_1_sva_1 & reg_1, STD_LOGIC_VECTOR'((fsm_output(2)) & (fsm_output(3))
      & or_tmp_1));
  z_out_1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(mux_9_nl) * UNSIGNED(mux1h_6_nl)),
      64));
END v11;

-- ------------------------------------------------------------------
--  Design Unit:    Adding
--  Generated from file(s):
--    2) $PROJECT_HOME/ESL.c
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.std_logic_arith.ALL;
LIBRARY mgc_hls;
USE mgc_hls.funcs.ALL;
USE work.adding_mux_pkg.ALL;


ENTITY Adding IS
  PORT(
    A_rsc_z : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    B_rsc_z : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    C_rsc_z : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    D_rsc_z : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    E_rsc_z : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    Temp_rsc_z : OUT STD_LOGIC_VECTOR (63 DOWNTO 0);
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC
  );
END Adding;

ARCHITECTURE v11 OF Adding IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL A_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL B_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL C_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL D_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL E_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL Temp_rsc_mgc_out_stdreg_d : STD_LOGIC_VECTOR (63 DOWNTO 0);

  SIGNAL A_rsc_mgc_in_wire_d_1 : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL A_rsc_mgc_in_wire_z : STD_LOGIC_VECTOR (7 DOWNTO 0);

  SIGNAL B_rsc_mgc_in_wire_d_1 : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL B_rsc_mgc_in_wire_z : STD_LOGIC_VECTOR (7 DOWNTO 0);

  SIGNAL C_rsc_mgc_in_wire_d_1 : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL C_rsc_mgc_in_wire_z : STD_LOGIC_VECTOR (7 DOWNTO 0);

  SIGNAL D_rsc_mgc_in_wire_d_1 : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL D_rsc_mgc_in_wire_z : STD_LOGIC_VECTOR (7 DOWNTO 0);

  SIGNAL E_rsc_mgc_in_wire_d_1 : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL E_rsc_mgc_in_wire_z : STD_LOGIC_VECTOR (7 DOWNTO 0);

  SIGNAL Temp_rsc_mgc_out_stdreg_d_1 : STD_LOGIC_VECTOR (63 DOWNTO 0);
  SIGNAL Temp_rsc_mgc_out_stdreg_z : STD_LOGIC_VECTOR (63 DOWNTO 0);

  COMPONENT Adding_core
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      A_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
      B_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
      C_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
      D_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
      E_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
      Temp_rsc_mgc_out_stdreg_d : OUT STD_LOGIC_VECTOR (63 DOWNTO 0)
    );
  END COMPONENT;
  SIGNAL Adding_core_inst_A_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL Adding_core_inst_B_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL Adding_core_inst_C_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL Adding_core_inst_D_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL Adding_core_inst_E_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL Adding_core_inst_Temp_rsc_mgc_out_stdreg_d : STD_LOGIC_VECTOR (63 DOWNTO
      0);

BEGIN
  -- Default Constant Signal Assignments

  A_rsc_mgc_in_wire : mgc_hls.mgc_ioport_comps.mgc_in_wire
    GENERIC MAP(
      rscid => 1,
      width => 8
      )
    PORT MAP(
      d => A_rsc_mgc_in_wire_d_1,
      z => A_rsc_mgc_in_wire_z
    );
  A_rsc_mgc_in_wire_d <= A_rsc_mgc_in_wire_d_1;
  A_rsc_mgc_in_wire_z <= A_rsc_z;

  B_rsc_mgc_in_wire : mgc_hls.mgc_ioport_comps.mgc_in_wire
    GENERIC MAP(
      rscid => 2,
      width => 8
      )
    PORT MAP(
      d => B_rsc_mgc_in_wire_d_1,
      z => B_rsc_mgc_in_wire_z
    );
  B_rsc_mgc_in_wire_d <= B_rsc_mgc_in_wire_d_1;
  B_rsc_mgc_in_wire_z <= B_rsc_z;

  C_rsc_mgc_in_wire : mgc_hls.mgc_ioport_comps.mgc_in_wire
    GENERIC MAP(
      rscid => 3,
      width => 8
      )
    PORT MAP(
      d => C_rsc_mgc_in_wire_d_1,
      z => C_rsc_mgc_in_wire_z
    );
  C_rsc_mgc_in_wire_d <= C_rsc_mgc_in_wire_d_1;
  C_rsc_mgc_in_wire_z <= C_rsc_z;

  D_rsc_mgc_in_wire : mgc_hls.mgc_ioport_comps.mgc_in_wire
    GENERIC MAP(
      rscid => 4,
      width => 8
      )
    PORT MAP(
      d => D_rsc_mgc_in_wire_d_1,
      z => D_rsc_mgc_in_wire_z
    );
  D_rsc_mgc_in_wire_d <= D_rsc_mgc_in_wire_d_1;
  D_rsc_mgc_in_wire_z <= D_rsc_z;

  E_rsc_mgc_in_wire : mgc_hls.mgc_ioport_comps.mgc_in_wire
    GENERIC MAP(
      rscid => 5,
      width => 8
      )
    PORT MAP(
      d => E_rsc_mgc_in_wire_d_1,
      z => E_rsc_mgc_in_wire_z
    );
  E_rsc_mgc_in_wire_d <= E_rsc_mgc_in_wire_d_1;
  E_rsc_mgc_in_wire_z <= E_rsc_z;

  Temp_rsc_mgc_out_stdreg : mgc_hls.mgc_ioport_comps.mgc_out_stdreg
    GENERIC MAP(
      rscid => 6,
      width => 64
      )
    PORT MAP(
      d => Temp_rsc_mgc_out_stdreg_d_1,
      z => Temp_rsc_mgc_out_stdreg_z
    );
  Temp_rsc_mgc_out_stdreg_d_1 <= Temp_rsc_mgc_out_stdreg_d;
  Temp_rsc_z <= Temp_rsc_mgc_out_stdreg_z;

  Adding_core_inst : adding_core
    PORT MAP(
      clk => clk,
      rst => rst,
      A_rsc_mgc_in_wire_d => Adding_core_inst_A_rsc_mgc_in_wire_d,
      B_rsc_mgc_in_wire_d => Adding_core_inst_B_rsc_mgc_in_wire_d,
      C_rsc_mgc_in_wire_d => Adding_core_inst_C_rsc_mgc_in_wire_d,
      D_rsc_mgc_in_wire_d => Adding_core_inst_D_rsc_mgc_in_wire_d,
      E_rsc_mgc_in_wire_d => Adding_core_inst_E_rsc_mgc_in_wire_d,
      Temp_rsc_mgc_out_stdreg_d => Adding_core_inst_Temp_rsc_mgc_out_stdreg_d
    );
  Adding_core_inst_A_rsc_mgc_in_wire_d <= A_rsc_mgc_in_wire_d;
  Adding_core_inst_B_rsc_mgc_in_wire_d <= B_rsc_mgc_in_wire_d;
  Adding_core_inst_C_rsc_mgc_in_wire_d <= C_rsc_mgc_in_wire_d;
  Adding_core_inst_D_rsc_mgc_in_wire_d <= D_rsc_mgc_in_wire_d;
  Adding_core_inst_E_rsc_mgc_in_wire_d <= E_rsc_mgc_in_wire_d;
  Temp_rsc_mgc_out_stdreg_d <= Adding_core_inst_Temp_rsc_mgc_out_stdreg_d;

END v11;



