directive set /Convolotion/Convolotion:core/core/Drow#1.sva#1 REGISTER_NAME reg#1
directive set /Convolotion/Convolotion:core/core/Drow#2.sva#1 REGISTER_NAME reg#1
directive set /Convolotion/Convolotion:core/core/Drow#3.sva#1 REGISTER_NAME reg#1
directive set /Convolotion/Convolotion:core/core/Drow#1.sva#2 REGISTER_NAME reg#2
directive set /Convolotion/Convolotion:core/core/Drow#2.sva#2 REGISTER_NAME reg#2
directive set /Convolotion/Convolotion:core/core/Drow#3.sva#2 REGISTER_NAME reg#2
directive set /Convolotion/Convolotion:core/core/Dcolumn#4.sva REGISTER_NAME reg#3
directive set /Convolotion/Convolotion:core/core/for-1:acc#1.psp.sva REGISTER_NAME reg#3
directive set /Convolotion/Convolotion:core/core/Krow#1.sva REGISTER_NAME reg#4
directive set /Convolotion/Convolotion:core/core/Krow#2.sva REGISTER_NAME reg#4
directive set /Convolotion/Convolotion:core/core/Krow#3.sva REGISTER_NAME reg#4
directive set /Convolotion/Convolotion:core/core/Krow#3.sva#1 REGISTER_NAME reg#4
directive set /Convolotion/Convolotion:core/core/Krow#1.sva#1 REGISTER_NAME reg#4
directive set /Convolotion/Convolotion:core/core/Krow#2.sva#1 REGISTER_NAME reg#4
directive set /Convolotion/Convolotion:core/core/Kcolumn#1.sva REGISTER_NAME reg#5
directive set /Convolotion/Convolotion:core/core/Kcolumn#2.sva REGISTER_NAME reg#5
directive set /Convolotion/Convolotion:core/core/Kcolumn#3.sva REGISTER_NAME reg#5
directive set /Convolotion/Convolotion:core/core/for:for:for:for:else:mux#2.itm REGISTER_NAME for:for:for:for:else.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:else:mux#4.itm REGISTER_NAME for:for:for:for:else.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:else:mux.itm REGISTER_NAME for:for:for:for:else.reg
directive set /Convolotion/Convolotion:core/core/Result#1.lpi#4 REGISTER_NAME reg#6
directive set /Convolotion/Convolotion:core/core/Result#1.lpi#4.dfm REGISTER_NAME reg#6
directive set /Convolotion/Convolotion:core/core/Result#2.lpi#4 REGISTER_NAME reg#6
directive set /Convolotion/Convolotion:core/core/Result#2.lpi#4.dfm REGISTER_NAME reg#6
directive set /Convolotion/Convolotion:core/core/Result#3.lpi#4 REGISTER_NAME reg#6
directive set /Convolotion/Convolotion:core/core/Result#3.lpi#4.dfm REGISTER_NAME reg#6
directive set /Convolotion/Convolotion:core/core/Result.sg2#1.lpi#4 REGISTER_NAME Result.reg
directive set /Convolotion/Convolotion:core/core/Result.sg2#1.lpi#4.dfm REGISTER_NAME Result.reg
directive set /Convolotion/Convolotion:core/core/Result.sg2#2.lpi#4 REGISTER_NAME Result.reg
directive set /Convolotion/Convolotion:core/core/Result.sg2#2.lpi#4.dfm REGISTER_NAME Result.reg
directive set /Convolotion/Convolotion:core/core/Result.sg2.lpi#4 REGISTER_NAME Result.reg
directive set /Convolotion/Convolotion:core/core/Result.sg2.lpi#4.dfm REGISTER_NAME Result.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:lor#3.lpi#4.dfm.st REGISTER_NAME for:for:for:for.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:lor#4.lpi#4.dfm.st REGISTER_NAME for:for:for:for.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:lor.lpi#4.dfm.st REGISTER_NAME for:for:for:for.reg
directive set /Convolotion/Convolotion:core/core/Result.sg1#1.lpi#4 REGISTER_NAME Result.reg#1
directive set /Convolotion/Convolotion:core/core/Result.sg1#1.lpi#4.dfm REGISTER_NAME Result.reg#1
directive set /Convolotion/Convolotion:core/core/Result.sg1#2.lpi#4 REGISTER_NAME Result.reg#1
directive set /Convolotion/Convolotion:core/core/Result.sg1#2.lpi#4.dfm REGISTER_NAME Result.reg#1
directive set /Convolotion/Convolotion:core/core/Result.sg1.lpi#4 REGISTER_NAME Result.reg#1
directive set /Convolotion/Convolotion:core/core/Result.sg1.lpi#4.dfm REGISTER_NAME Result.reg#1
directive set /Convolotion/Convolotion:core/core/for-1:for:for:for:slc.itm REGISTER_NAME reg#7
directive set /Convolotion/Convolotion:core/core/for-2:for:for:for:slc.itm REGISTER_NAME reg#7
directive set /Convolotion/Convolotion:core/core/for-3:for:for:for:slc.itm REGISTER_NAME reg#7
directive set /Convolotion/Convolotion:core/core/for:for:for:for:else:mux#1.itm REGISTER_NAME for:for:for:for:else.reg#1
directive set /Convolotion/Convolotion:core/core/for:for:for:for:else:mux#3.itm REGISTER_NAME for:for:for:for:else.reg#1
directive set /Convolotion/Convolotion:core/core/for:for:for:for:else:mux#5.itm REGISTER_NAME for:for:for:for:else.reg#1
