-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    2011a.41 Production Release
--  HLS Date:       Thu Apr  7 20:28:55 PDT 2011
-- 
--  Generated by:   ss@DESKTOP-UB05SU4
--  Generated date: Sat Apr 20 18:41:42 2019
-- ----------------------------------------------------------------------

-- 
-- ------------------------------------------------------------------
--  Design Unit:    Convolotion_core_fsm
--  FSM Module
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.std_logic_arith.ALL;
LIBRARY mgc_hls;
USE mgc_hls.funcs.ALL;
USE work.convolotion_mux_pkg.ALL;


ENTITY Convolotion_core_fsm IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    fsm_output : OUT STD_LOGIC_VECTOR (16 DOWNTO 0);
    st_for_for_1_for_for_1_tr0 : IN STD_LOGIC;
    st_for_for_1_for_tr0 : IN STD_LOGIC;
    st_for_for_2_for_tr0 : IN STD_LOGIC;
    st_for_for_3_tr0 : IN STD_LOGIC;
    st_for_for_3_for_tr0 : IN STD_LOGIC;
    st_for_tr0 : IN STD_LOGIC
  );
END Convolotion_core_fsm;

ARCHITECTURE v12 OF Convolotion_core_fsm IS
  -- Default Constants

  -- FSM State Type Declaration for Convolotion_core_fsm_1
  TYPE Convolotion_core_fsm_1_ST IS (st_main, st_for_for_1_for_for, st_for_for_1_for_for_1,
      st_for_for_1_for, st_for_for, st_for_for_1, st_for_for_2_for_for, st_for_for_2_for_for_1,
      st_for_for_2_for, st_for_for_2, st_for_for_3, st_for_for_3_for_for, st_for_for_3_for_for_1,
      st_for_for_3_for, st_for_for_4, st_for_for_5, st_for);

  SIGNAL state_var : Convolotion_core_fsm_1_ST;
  SIGNAL state_var_NS : Convolotion_core_fsm_1_ST;

BEGIN
  -- Default Constant Signal Assignments

  Convolotion_core_fsm_1 : PROCESS (st_for_for_1_for_for_1_tr0, st_for_for_1_for_tr0,
      st_for_for_2_for_tr0, st_for_for_3_tr0, st_for_for_3_for_tr0, st_for_tr0, state_var)
  BEGIN
    CASE state_var IS
      WHEN st_main =>
        fsm_output <= STD_LOGIC_VECTOR'("00000000000000001");
        state_var_NS <= st_for_for_1_for_for;
      WHEN st_for_for_1_for_for =>
        fsm_output <= STD_LOGIC_VECTOR'("00000000000000010");
        state_var_NS <= st_for_for_1_for_for_1;
      WHEN st_for_for_1_for_for_1 =>
        fsm_output <= STD_LOGIC_VECTOR'("00000000000000100");
        IF ( st_for_for_1_for_for_1_tr0 = '1' ) THEN
          state_var_NS <= st_for_for_1_for;
        ELSE
          state_var_NS <= st_for_for_1_for_for;
        END IF;
      WHEN st_for_for_1_for =>
        fsm_output <= STD_LOGIC_VECTOR'("00000000000001000");
        IF ( st_for_for_1_for_tr0 = '1' ) THEN
          state_var_NS <= st_for_for;
        ELSE
          state_var_NS <= st_for_for_1_for_for;
        END IF;
      WHEN st_for_for =>
        fsm_output <= STD_LOGIC_VECTOR'("00000000000010000");
        state_var_NS <= st_for_for_1;
      WHEN st_for_for_1 =>
        fsm_output <= STD_LOGIC_VECTOR'("00000000000100000");
        state_var_NS <= st_for_for_2_for_for;
      WHEN st_for_for_2_for_for =>
        fsm_output <= STD_LOGIC_VECTOR'("00000000001000000");
        state_var_NS <= st_for_for_2_for_for_1;
      WHEN st_for_for_2_for_for_1 =>
        fsm_output <= STD_LOGIC_VECTOR'("00000000010000000");
        IF ( st_for_for_1_for_for_1_tr0 = '1' ) THEN
          state_var_NS <= st_for_for_2_for;
        ELSE
          state_var_NS <= st_for_for_2_for_for;
        END IF;
      WHEN st_for_for_2_for =>
        fsm_output <= STD_LOGIC_VECTOR'("00000000100000000");
        IF ( st_for_for_2_for_tr0 = '1' ) THEN
          state_var_NS <= st_for_for_2;
        ELSE
          state_var_NS <= st_for_for_2_for_for;
        END IF;
      WHEN st_for_for_2 =>
        fsm_output <= STD_LOGIC_VECTOR'("00000001000000000");
        state_var_NS <= st_for_for_3;
      WHEN st_for_for_3 =>
        fsm_output <= STD_LOGIC_VECTOR'("00000010000000000");
        IF ( st_for_for_3_tr0 = '1' ) THEN
          state_var_NS <= st_for;
        ELSE
          state_var_NS <= st_for_for_3_for_for;
        END IF;
      WHEN st_for_for_3_for_for =>
        fsm_output <= STD_LOGIC_VECTOR'("00000100000000000");
        state_var_NS <= st_for_for_3_for_for_1;
      WHEN st_for_for_3_for_for_1 =>
        fsm_output <= STD_LOGIC_VECTOR'("00001000000000000");
        IF ( st_for_for_1_for_for_1_tr0 = '1' ) THEN
          state_var_NS <= st_for_for_3_for;
        ELSE
          state_var_NS <= st_for_for_3_for_for;
        END IF;
      WHEN st_for_for_3_for =>
        fsm_output <= STD_LOGIC_VECTOR'("00010000000000000");
        IF ( st_for_for_3_for_tr0 = '1' ) THEN
          state_var_NS <= st_for_for_4;
        ELSE
          state_var_NS <= st_for_for_3_for_for;
        END IF;
      WHEN st_for_for_4 =>
        fsm_output <= STD_LOGIC_VECTOR'("00100000000000000");
        state_var_NS <= st_for_for_5;
      WHEN st_for_for_5 =>
        fsm_output <= STD_LOGIC_VECTOR'("01000000000000000");
        state_var_NS <= st_for_for_1_for_for;
      WHEN st_for =>
        fsm_output <= STD_LOGIC_VECTOR'("10000000000000000");
        IF ( st_for_tr0 = '1' ) THEN
          state_var_NS <= st_main;
        ELSE
          state_var_NS <= st_for_for_1_for_for;
        END IF;
      WHEN OTHERS =>
        fsm_output <= "00000000000000000";
        state_var_NS <= st_main;
    END CASE;
  END PROCESS Convolotion_core_fsm_1;

  Convolotion_core_fsm_1_REG : PROCESS (clk)
  BEGIN
    IF clk'event AND ( clk = '1' ) THEN
      IF ( rst = '1' ) THEN
        state_var <= st_main;
      ELSE
        state_var <= state_var_NS;
      END IF;
    END IF;
  END PROCESS Convolotion_core_fsm_1_REG;

END v12;

-- ------------------------------------------------------------------
--  Design Unit:    Convolotion_core
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.std_logic_arith.ALL;
LIBRARY mgc_hls;
USE mgc_hls.funcs.ALL;
USE work.convolotion_mux_pkg.ALL;


ENTITY Convolotion_core IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    in_rsc_singleport_addr : OUT STD_LOGIC_VECTOR (17 DOWNTO 0);
    in_rsc_singleport_re : OUT STD_LOGIC;
    in_rsc_singleport_data_out : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    out_rsc_singleport_data_in : OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
    out_rsc_singleport_addr : OUT STD_LOGIC_VECTOR (17 DOWNTO 0);
    out_rsc_singleport_we : OUT STD_LOGIC
  );
END Convolotion_core;

ARCHITECTURE v12 OF Convolotion_core IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL fsm_output : STD_LOGIC_VECTOR (16 DOWNTO 0);
  SIGNAL or_dcpl_32 : STD_LOGIC;
  SIGNAL and_dcpl_22 : STD_LOGIC;
  SIGNAL reg_1 : STD_LOGIC_VECTOR (8 DOWNTO 0);
  SIGNAL Result_reg_1 : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL Result_reg : STD_LOGIC;
  SIGNAL Drow_1_sva : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL reg_3 : STD_LOGIC_VECTOR (1 DOWNTO 0);
  SIGNAL reg_4 : STD_LOGIC;
  SIGNAL reg_2 : STD_LOGIC_VECTOR (1 DOWNTO 0);
  SIGNAL for_for_for_for_else_reg_1 : STD_LOGIC;
  SIGNAL for_reg : STD_LOGIC;
  SIGNAL for_for_for_for_reg : STD_LOGIC;
  SIGNAL for_for_for_for_else_reg : STD_LOGIC_VECTOR (1 DOWNTO 0);
  SIGNAL Dcolumn_1_sva_2 : STD_LOGIC_VECTOR (8 DOWNTO 0);
  SIGNAL or_34_cse : STD_LOGIC;
  SIGNAL and_13_cse : STD_LOGIC;
  SIGNAL for_for_3_for_for_oelse_2_acc_itm : STD_LOGIC_VECTOR (1 DOWNTO 0);
  SIGNAL z_out : STD_LOGIC_VECTOR (2 DOWNTO 0);
  SIGNAL z_out_1 : STD_LOGIC_VECTOR (3 DOWNTO 0);
  SIGNAL z_out_2 : STD_LOGIC_VECTOR (10 DOWNTO 0);
  SIGNAL z_out_3 : STD_LOGIC_VECTOR (10 DOWNTO 0);
  SIGNAL for_for_for_for_else_acc_sdt : STD_LOGIC_VECTOR (2 DOWNTO 0);
  SIGNAL for_for_for_for_else_ac_fixed_cctor_1_sva : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL slc_sat_1_sva : STD_LOGIC_VECTOR (8 DOWNTO 0);
  SIGNAL for_for_for_for_else_acc_itm : STD_LOGIC_VECTOR (2 DOWNTO 0);

  SIGNAL mux_16_nl : STD_LOGIC_VECTOR (8 DOWNTO 0);
  SIGNAL mux_10_nl : STD_LOGIC_VECTOR (1 DOWNTO 0);
  SIGNAL mux_21_nl : STD_LOGIC_VECTOR (8 DOWNTO 0);
  SIGNAL mux_25_nl : STD_LOGIC_VECTOR (1 DOWNTO 0);
  SIGNAL mux_9_nl : STD_LOGIC_VECTOR (1 DOWNTO 0);
  COMPONENT Convolotion_core_fsm
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      fsm_output : OUT STD_LOGIC_VECTOR (16 DOWNTO 0);
      st_for_for_1_for_for_1_tr0 : IN STD_LOGIC;
      st_for_for_1_for_tr0 : IN STD_LOGIC;
      st_for_for_2_for_tr0 : IN STD_LOGIC;
      st_for_for_3_tr0 : IN STD_LOGIC;
      st_for_for_3_for_tr0 : IN STD_LOGIC;
      st_for_tr0 : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL Convolotion_core_fsm_inst_fsm_output : STD_LOGIC_VECTOR (16 DOWNTO 0);
  SIGNAL Convolotion_core_fsm_inst_st_for_for_1_for_for_1_tr0 : STD_LOGIC;
  SIGNAL Convolotion_core_fsm_inst_st_for_for_1_for_tr0 : STD_LOGIC;
  SIGNAL Convolotion_core_fsm_inst_st_for_for_2_for_tr0 : STD_LOGIC;
  SIGNAL Convolotion_core_fsm_inst_st_for_for_3_tr0 : STD_LOGIC;
  SIGNAL Convolotion_core_fsm_inst_st_for_for_3_for_tr0 : STD_LOGIC;
  SIGNAL Convolotion_core_fsm_inst_st_for_tr0 : STD_LOGIC;

BEGIN
  -- Default Constant Signal Assignments

  Convolotion_core_fsm_inst : convolotion_core_fsm
    PORT MAP(
      clk => clk,
      rst => rst,
      fsm_output => Convolotion_core_fsm_inst_fsm_output,
      st_for_for_1_for_for_1_tr0 => Convolotion_core_fsm_inst_st_for_for_1_for_for_1_tr0,
      st_for_for_1_for_tr0 => Convolotion_core_fsm_inst_st_for_for_1_for_tr0,
      st_for_for_2_for_tr0 => Convolotion_core_fsm_inst_st_for_for_2_for_tr0,
      st_for_for_3_tr0 => Convolotion_core_fsm_inst_st_for_for_3_tr0,
      st_for_for_3_for_tr0 => Convolotion_core_fsm_inst_st_for_for_3_for_tr0,
      st_for_tr0 => Convolotion_core_fsm_inst_st_for_tr0
    );
  fsm_output <= Convolotion_core_fsm_inst_fsm_output;
  Convolotion_core_fsm_inst_st_for_for_1_for_for_1_tr0 <= NOT for_reg;
  Convolotion_core_fsm_inst_st_for_for_1_for_tr0 <= NOT (z_out_1(2));
  Convolotion_core_fsm_inst_st_for_for_2_for_tr0 <= NOT (z_out_1(2));
  Convolotion_core_fsm_inst_st_for_for_3_tr0 <= Drow_1_sva(9);
  Convolotion_core_fsm_inst_st_for_for_3_for_tr0 <= NOT (z_out_1(2));
  Convolotion_core_fsm_inst_st_for_tr0 <= z_out_3(9);

  or_34_cse <= or_dcpl_32 OR (fsm_output(15)) OR (fsm_output(5)) OR (fsm_output(10));
  and_13_cse <= (NOT((NOT((NOT((fsm_output(7)) OR (fsm_output(12)) OR (fsm_output(2))))
      OR for_for_for_for_reg)) OR (fsm_output(0)))) AND (NOT((fsm_output(16)) OR
      (fsm_output(15)))) AND (NOT((fsm_output(5)) OR (fsm_output(10))));
  for_for_for_for_else_acc_sdt <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(reg_2),
      3) + CONV_UNSIGNED(UNSIGNED(reg_3), 3), 3));
  for_for_for_for_else_acc_itm <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(for_for_for_for_else_acc_sdt(2
      DOWNTO 1)), 3) + CONV_UNSIGNED(UNSIGNED(reg_2), 3), 3));
  for_for_for_for_else_ac_fixed_cctor_1_sva <= (slc_sat_1_sva(7 DOWNTO 0)) OR STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(slc_sat_1_sva(8),
      1),8));
  slc_sat_1_sva <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(Result_reg)
      & Result_reg_1 & TO_STDLOGICVECTOR(reg_4)), 9) + CONV_UNSIGNED(UNSIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(in_rsc_singleport_data_out)
      * UNSIGNED(for_for_for_for_else_reg & TO_STDLOGICVECTOR('0') & STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(for_for_for_for_else_reg_1,
      1),2)))), 12)), 7, 5)), 9), 9));
  for_for_3_for_for_oelse_2_acc_itm <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(NOT (z_out_2(10
      DOWNTO 9))) + CONV_SIGNED(CONV_UNSIGNED('1', 1), 2), 2));
  or_dcpl_32 <= (fsm_output(0)) OR (fsm_output(16));
  and_dcpl_22 <= NOT((fsm_output(0)) OR (fsm_output(16)));
  in_rsc_singleport_addr <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(z_out_2(8 DOWNTO
      0)) + CONV_UNSIGNED(SIGNED(z_out_3(10 DOWNTO 9)), 9), 9)) & (z_out_3(8 DOWNTO
      0));
  in_rsc_singleport_re <= NOT((((NOT((z_out_2(10)) OR (for_for_3_for_for_oelse_2_acc_itm(1))))
      AND (fsm_output(11))) OR ((fsm_output(6)) AND (NOT (z_out_2(9)))) OR ((fsm_output(1))
      AND (NOT (z_out_2(9))))) AND (NOT((z_out_3(9)) OR (z_out_3(10)))));
  out_rsc_singleport_data_in <= TO_STDLOGICVECTOR(Result_reg) & Result_reg_1 & TO_STDLOGICVECTOR(reg_4);
  mux_16_nl <= MUX_v_9_2_2(reg_1 & (Drow_1_sva(8 DOWNTO 0)), fsm_output(14));
  out_rsc_singleport_addr <= (mux_16_nl) & Dcolumn_1_sva_2;
  out_rsc_singleport_we <= NOT((fsm_output(14)) OR (fsm_output(4)) OR (fsm_output(9)));
  PROCESS (clk)
  BEGIN
    IF clk'EVENT AND ( clk = '1' ) THEN
      IF (rst = '1') THEN
        Result_reg_1 <= STD_LOGIC_VECTOR'("000000");
        Result_reg <= '0';
        Dcolumn_1_sva_2 <= STD_LOGIC_VECTOR'("000000000");
        reg_1 <= STD_LOGIC_VECTOR'("000000000");
        reg_2 <= STD_LOGIC_VECTOR'("00");
        reg_3 <= STD_LOGIC_VECTOR'("00");
        reg_4 <= '0';
        for_for_for_for_else_reg_1 <= '0';
        for_reg <= '0';
        for_for_for_for_else_reg <= STD_LOGIC_VECTOR'("00");
        for_for_for_for_reg <= '0';
        Drow_1_sva <= STD_LOGIC_VECTOR'("0000000000");
      ELSE
        Result_reg_1 <= (MUX_v_6_2_2((for_for_for_for_else_ac_fixed_cctor_1_sva(6
            DOWNTO 1)) & Result_reg_1, and_13_cse)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            or_34_cse, 1),6));
        Result_reg <= (MUX_s_1_2_2(STD_LOGIC_VECTOR'((for_for_for_for_else_ac_fixed_cctor_1_sva(7))
            & Result_reg), and_13_cse)) AND (NOT or_34_cse);
        Dcolumn_1_sva_2 <= (MUX_v_9_2_2((z_out_3(8 DOWNTO 0)) & Dcolumn_1_sva_2,
            and_dcpl_22)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT (fsm_output(0)),
            1),9));
        reg_1 <= (MUX_v_9_2_2(reg_1 & (z_out_2(8 DOWNTO 0)), NOT((NOT((fsm_output(4))
            OR (fsm_output(14)))) OR or_dcpl_32))) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            or_dcpl_32, 1),9));
        reg_2 <= (MUX_v_2_2_2((z_out(1 DOWNTO 0)) & reg_2, (fsm_output(7)) OR (fsm_output(12))
            OR (fsm_output(2)))) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT(or_dcpl_32
            OR (fsm_output(15)) OR (fsm_output(5)) OR (fsm_output(13)) OR (fsm_output(8))
            OR (fsm_output(3)) OR (fsm_output(10))), 1),2));
        reg_3 <= (MUX_v_2_2_2((z_out(1 DOWNTO 0)) & reg_3, and_dcpl_22 AND (NOT((fsm_output(15))
            OR (fsm_output(5)))) AND (NOT((fsm_output(13)) OR (fsm_output(8)))) AND
            (NOT((fsm_output(3)) OR (fsm_output(10)))))) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            or_34_cse, 1),2));
        reg_4 <= (MUX_s_1_2_2(STD_LOGIC_VECTOR'((for_for_for_for_else_ac_fixed_cctor_1_sva(0))
            & reg_4), and_13_cse)) AND (NOT or_34_cse);
        for_for_for_for_else_reg_1 <= MUX_s_1_16_2(STD_LOGIC_VECTOR'('0' & '0' &
            '0' & '0' & '1' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0'
            & '0' & '0'), for_for_for_for_else_acc_itm & TO_STDLOGICVECTOR(for_for_for_for_else_acc_sdt(0)));
        for_reg <= z_out_1(2);
        for_for_for_for_else_reg <= MUX_v_2_16_2(STD_LOGIC_VECTOR'("01") & STD_LOGIC_VECTOR'("10")
            & STD_LOGIC_VECTOR'("01") & STD_LOGIC_VECTOR'("10") & STD_LOGIC_VECTOR'("00")
            & STD_LOGIC_VECTOR'("10") & STD_LOGIC_VECTOR'("01") & STD_LOGIC_VECTOR'("10")
            & STD_LOGIC_VECTOR'("01") & STD_LOGIC_VECTOR'("00") & STD_LOGIC_VECTOR'("00")
            & STD_LOGIC_VECTOR'("00") & STD_LOGIC_VECTOR'("00") & STD_LOGIC_VECTOR'("00")
            & STD_LOGIC_VECTOR'("00") & STD_LOGIC_VECTOR'("00"), for_for_for_for_else_acc_itm
            & TO_STDLOGICVECTOR(for_for_for_for_else_acc_sdt(0)));
        for_for_for_for_reg <= MUX_s_1_2_2(STD_LOGIC_VECTOR'(((z_out_2(9)) OR (z_out_3(9))
            OR (z_out_3(10))) & ((for_for_3_for_for_oelse_2_acc_itm(1)) OR (z_out_2(10))
            OR (z_out_3(9)) OR (z_out_3(10)))), fsm_output(11));
        Drow_1_sva <= MUX_v_10_2_2((z_out_2(9 DOWNTO 0)) & Drow_1_sva, (fsm_output(13))
            OR (fsm_output(10)) OR (fsm_output(12)) OR (fsm_output(11)));
      END IF;
    END IF;
  END PROCESS;
  mux_10_nl <= MUX_v_2_2_2(reg_2 & reg_3, (fsm_output(3)) OR (fsm_output(8)) OR (fsm_output(13)));
  z_out <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(mux_10_nl), 3) +
      UNSIGNED'("001"), 3));
  z_out_1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR('1')
      & (z_out(1 DOWNTO 0))), 4) + UNSIGNED'("0001"), 4));
  mux_21_nl <= MUX_v_9_2_2(reg_1 & (Drow_1_sva(8 DOWNTO 0)), (fsm_output(14)) OR
      (fsm_output(11)));
  mux_25_nl <= MUX_v_2_2_2(STD_LOGIC_VECTOR'("01") & STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(reg_2)
      + CONV_SIGNED(CONV_SIGNED('1', 1), 2), 2)), (fsm_output(1)) OR (fsm_output(6))
      OR (fsm_output(11)));
  z_out_2 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(mux_21_nl), 11)
      + CONV_UNSIGNED(SIGNED(mux_25_nl), 11), 11));
  mux_9_nl <= MUX_v_2_2_2(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(reg_3) + CONV_SIGNED(CONV_SIGNED('1',
      1), 2), 2)) & STD_LOGIC_VECTOR'("01"), fsm_output(16));
  z_out_3 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(Dcolumn_1_sva_2),
      11) + CONV_UNSIGNED(SIGNED(mux_9_nl), 11), 11));
END v12;

-- ------------------------------------------------------------------
--  Design Unit:    Convolotion
--  Generated from file(s):
--    2) $PROJECT_HOME/ESL_CA2.c
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.std_logic_arith.ALL;
LIBRARY mgc_hls;
USE mgc_hls.funcs.ALL;
USE work.convolotion_mux_pkg.ALL;


ENTITY Convolotion IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;
    in_rsc_singleport_data_in : OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
    in_rsc_singleport_addr : OUT STD_LOGIC_VECTOR (17 DOWNTO 0);
    in_rsc_singleport_re : OUT STD_LOGIC;
    in_rsc_singleport_we : OUT STD_LOGIC;
    in_rsc_singleport_data_out : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    out_rsc_singleport_data_in : OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
    out_rsc_singleport_addr : OUT STD_LOGIC_VECTOR (17 DOWNTO 0);
    out_rsc_singleport_re : OUT STD_LOGIC;
    out_rsc_singleport_we : OUT STD_LOGIC;
    out_rsc_singleport_data_out : IN STD_LOGIC_VECTOR (7 DOWNTO 0)
  );
END Convolotion;

ARCHITECTURE v12 OF Convolotion IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL in_rsc_singleport_addr_reg : STD_LOGIC_VECTOR (17 DOWNTO 0);
  SIGNAL in_rsc_singleport_re_reg : STD_LOGIC;
  SIGNAL out_rsc_singleport_data_in_reg : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL out_rsc_singleport_addr_reg : STD_LOGIC_VECTOR (17 DOWNTO 0);
  SIGNAL out_rsc_singleport_we_reg : STD_LOGIC;

  COMPONENT Convolotion_core
    PORT(
      clk : IN STD_LOGIC;
      rst : IN STD_LOGIC;
      in_rsc_singleport_addr : OUT STD_LOGIC_VECTOR (17 DOWNTO 0);
      in_rsc_singleport_re : OUT STD_LOGIC;
      in_rsc_singleport_data_out : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
      out_rsc_singleport_data_in : OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
      out_rsc_singleport_addr : OUT STD_LOGIC_VECTOR (17 DOWNTO 0);
      out_rsc_singleport_we : OUT STD_LOGIC
    );
  END COMPONENT;
  SIGNAL Convolotion_core_inst_in_rsc_singleport_addr : STD_LOGIC_VECTOR (17 DOWNTO
      0);
  SIGNAL Convolotion_core_inst_in_rsc_singleport_data_out : STD_LOGIC_VECTOR (7 DOWNTO
      0);
  SIGNAL Convolotion_core_inst_out_rsc_singleport_data_in : STD_LOGIC_VECTOR (7 DOWNTO
      0);
  SIGNAL Convolotion_core_inst_out_rsc_singleport_addr : STD_LOGIC_VECTOR (17 DOWNTO
      0);

BEGIN
  -- Default Constant Signal Assignments

  Convolotion_core_inst : convolotion_core
    PORT MAP(
      clk => clk,
      rst => rst,
      in_rsc_singleport_addr => Convolotion_core_inst_in_rsc_singleport_addr,
      in_rsc_singleport_re => in_rsc_singleport_re_reg,
      in_rsc_singleport_data_out => Convolotion_core_inst_in_rsc_singleport_data_out,
      out_rsc_singleport_data_in => Convolotion_core_inst_out_rsc_singleport_data_in,
      out_rsc_singleport_addr => Convolotion_core_inst_out_rsc_singleport_addr,
      out_rsc_singleport_we => out_rsc_singleport_we_reg
    );
  in_rsc_singleport_addr_reg <= Convolotion_core_inst_in_rsc_singleport_addr;
  Convolotion_core_inst_in_rsc_singleport_data_out <= in_rsc_singleport_data_out;
  out_rsc_singleport_data_in_reg <= Convolotion_core_inst_out_rsc_singleport_data_in;
  out_rsc_singleport_addr_reg <= Convolotion_core_inst_out_rsc_singleport_addr;

  in_rsc_singleport_data_in <= STD_LOGIC_VECTOR'("00000000");
  in_rsc_singleport_addr <= in_rsc_singleport_addr_reg;
  in_rsc_singleport_re <= in_rsc_singleport_re_reg;
  in_rsc_singleport_we <= '1';
  out_rsc_singleport_data_in <= out_rsc_singleport_data_in_reg;
  out_rsc_singleport_addr <= out_rsc_singleport_addr_reg;
  out_rsc_singleport_re <= '1';
  out_rsc_singleport_we <= out_rsc_singleport_we_reg;
END v12;



