// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.41 Production Release
//  HLS Date:       Thu Apr  7 20:28:55 PDT 2011
// 
//  Generated by:   ss@DESKTOP-UB05SU4
//  Generated date: Tue Apr 09 15:59:09 2019
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    Adding_core
// ------------------------------------------------------------------


module Adding_core (
  clk, rst, A_rsc_mgc_in_wire_d, B_rsc_mgc_in_wire_d, C_rsc_mgc_in_wire_d, D_rsc_mgc_in_wire_d,
      E_rsc_mgc_in_wire_d, Temp_rsc_mgc_out_stdreg_d
);
  input clk;
  input rst;
  input [7:0] A_rsc_mgc_in_wire_d;
  input [7:0] B_rsc_mgc_in_wire_d;
  input [7:0] C_rsc_mgc_in_wire_d;
  input [7:0] D_rsc_mgc_in_wire_d;
  input [7:0] E_rsc_mgc_in_wire_d;
  output [63:0] Temp_rsc_mgc_out_stdreg_d;
  reg [63:0] Temp_rsc_mgc_out_stdreg_d;


  always begin : core
    // Interconnect Declarations
    reg [7:0] A_1_sva;
    reg [7:0] B_1_sva;
    reg [7:0] C_1_sva;
    reg [7:0] D_1_sva;
    reg [7:0] E_1_sva;
    reg [2:0] in_i_2_sva;
    reg [63:0] Temp2_1_sva_1;
    reg [2:0] in_i_2_sva_1;
    reg [15:0] out_1_mul_1_cse_sva;
    reg [63:0] Temp2_2_sva;
    reg [2:0] in_i_3_sva;
    reg [63:0] Temp2_2_sva_1;
    reg [2:0] in_i_3_sva_1;
    reg [63:0] Temp2_3_sva;
    reg [2:0] in_i_4_sva;
    reg [63:0] Temp2_3_sva_1;
    reg [2:0] in_i_4_sva_1;
    reg [63:0] Temp2_4_sva;
    reg [2:0] in_i_5_sva;
    reg [63:0] Temp2_4_sva_1;
    reg [2:0] in_i_5_sva_1;
    reg [63:0] Temp2_5_sva;
    reg [2:0] in_i_6_sva;
    reg [63:0] Temp2_5_sva_1;
    reg [2:0] in_i_6_sva_1;
    reg [63:0] Temp2_6_sva;
    reg [2:0] in_i_7_sva;
    reg [63:0] Temp2_6_sva_1;
    reg [2:0] in_i_7_sva_1;
    reg [63:0] Temp2_7_sva;
    reg [2:0] in_i_8_sva;
    reg [63:0] Temp2_7_sva_1;
    reg [2:0] in_i_8_sva_1;
    reg [63:0] Temp2_8_sva;
    reg [2:0] in_i_9_sva;
    reg [63:0] Temp2_8_sva_1;
    reg [2:0] in_i_9_sva_1;
    reg [63:0] Temp2_9_sva;
    reg [2:0] in_i_10_sva;
    reg [63:0] Temp2_9_sva_1;
    reg [2:0] in_i_10_sva_1;
    reg [63:0] Temp2_10_sva;
    reg [2:0] in_i_11_sva;
    reg [63:0] Temp2_10_sva_1;
    reg [2:0] in_i_11_sva_1;
    reg [63:0] Temp2_11_sva;
    reg [2:0] in_i_1_sva;
    reg [63:0] Temp2_11_sva_1;
    reg [2:0] in_i_1_sva_1;

    begin : mainExit
      forever begin : main
        // C-Step 0 of Loop 'main'
        begin : waitLoop0Exit
          forever begin : waitLoop0
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop0Exit;
          end
        end
        // C-Step 1 of Loop 'main'
        A_1_sva = A_rsc_mgc_in_wire_d;
        B_1_sva = B_rsc_mgc_in_wire_d;
        C_1_sva = C_rsc_mgc_in_wire_d;
        D_1_sva = D_rsc_mgc_in_wire_d;
        E_1_sva = E_rsc_mgc_in_wire_d;
        in_i_2_sva = 3'b0;
        begin : out_1_inExit
          forever begin : out_1_in
            // C-Step 0 of Loop 'out_1_in'
            begin : waitLoop1Exit
              forever begin : waitLoop1
                @(posedge clk);
                if ( rst )
                  disable mainExit;
                if ( clk )
                  disable waitLoop1Exit;
              end
            end
            // C-Step 1 of Loop 'out_1_in'
            Temp2_1_sva_1 = Temp2_1_sva_1 + conv_u2u_9_64(readslicef_11_9_2((conv_u2u_10_11({(conv_u2u_8_9(A_1_sva)
                + conv_u2u_7_9(B_1_sva[7:1])) , (B_1_sva[0])}) + conv_u2u_9_11(conv_u2u_8_9(C_1_sva)
                + conv_u2u_8_9(D_1_sva)))));
            in_i_2_sva_1 = in_i_2_sva + 3'b1;
            if ( ~ (readslicef_3_1_2((({1'b1 , (in_i_2_sva_1[2:1])}) + 3'b1))) )
              disable out_1_inExit;
            in_i_2_sva = in_i_2_sva_1;
          end
        end
        begin : waitLoop2Exit
          forever begin : waitLoop2
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop2Exit;
          end
        end
        // C-Step 2 of Loop 'main'
        out_1_mul_1_cse_sva = conv_u2u_32_16(conv_u2u_8_16(E_1_sva) * conv_u2u_8_16(E_1_sva));
        Temp2_2_sva = conv_u2u_128_64(Temp2_1_sva_1 * conv_u2u_16_64(out_1_mul_1_cse_sva));
        in_i_3_sva = 3'b0;
        begin : out_2_inExit
          forever begin : out_2_in
            // C-Step 0 of Loop 'out_2_in'
            begin : waitLoop3Exit
              forever begin : waitLoop3
                @(posedge clk);
                if ( rst )
                  disable mainExit;
                if ( clk )
                  disable waitLoop3Exit;
              end
            end
            // C-Step 1 of Loop 'out_2_in'
            Temp2_2_sva_1 = Temp2_2_sva + conv_u2u_9_64(readslicef_11_9_2((conv_u2u_10_11({(conv_u2u_8_9(A_1_sva)
                + conv_u2u_7_9(B_1_sva[7:1])) , (B_1_sva[0])}) + conv_u2u_9_11(conv_u2u_8_9(C_1_sva)
                + conv_u2u_8_9(D_1_sva)))));
            in_i_3_sva_1 = in_i_3_sva + 3'b1;
            if ( ~ (readslicef_3_1_2((({1'b1 , (in_i_3_sva_1[2:1])}) + 3'b1))) )
              disable out_2_inExit;
            in_i_3_sva = in_i_3_sva_1;
            Temp2_2_sva = Temp2_2_sva_1;
          end
        end
        begin : waitLoop4Exit
          forever begin : waitLoop4
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop4Exit;
          end
        end
        // C-Step 3 of Loop 'main'
        Temp2_3_sva = conv_u2u_128_64(Temp2_2_sva_1 * conv_u2u_16_64(out_1_mul_1_cse_sva));
        in_i_4_sva = 3'b0;
        begin : out_3_inExit
          forever begin : out_3_in
            // C-Step 0 of Loop 'out_3_in'
            begin : waitLoop5Exit
              forever begin : waitLoop5
                @(posedge clk);
                if ( rst )
                  disable mainExit;
                if ( clk )
                  disable waitLoop5Exit;
              end
            end
            // C-Step 1 of Loop 'out_3_in'
            Temp2_3_sva_1 = Temp2_3_sva + conv_u2u_9_64(readslicef_11_9_2((conv_u2u_10_11({(conv_u2u_8_9(A_1_sva)
                + conv_u2u_7_9(B_1_sva[7:1])) , (B_1_sva[0])}) + conv_u2u_9_11(conv_u2u_8_9(C_1_sva)
                + conv_u2u_8_9(D_1_sva)))));
            in_i_4_sva_1 = in_i_4_sva + 3'b1;
            if ( ~ (readslicef_3_1_2((({1'b1 , (in_i_4_sva_1[2:1])}) + 3'b1))) )
              disable out_3_inExit;
            in_i_4_sva = in_i_4_sva_1;
            Temp2_3_sva = Temp2_3_sva_1;
          end
        end
        begin : waitLoop6Exit
          forever begin : waitLoop6
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop6Exit;
          end
        end
        // C-Step 4 of Loop 'main'
        Temp2_4_sva = conv_u2u_128_64(Temp2_3_sva_1 * conv_u2u_16_64(out_1_mul_1_cse_sva));
        in_i_5_sva = 3'b0;
        begin : out_4_inExit
          forever begin : out_4_in
            // C-Step 0 of Loop 'out_4_in'
            begin : waitLoop7Exit
              forever begin : waitLoop7
                @(posedge clk);
                if ( rst )
                  disable mainExit;
                if ( clk )
                  disable waitLoop7Exit;
              end
            end
            // C-Step 1 of Loop 'out_4_in'
            Temp2_4_sva_1 = Temp2_4_sva + conv_u2u_9_64(readslicef_11_9_2((conv_u2u_10_11({(conv_u2u_8_9(A_1_sva)
                + conv_u2u_7_9(B_1_sva[7:1])) , (B_1_sva[0])}) + conv_u2u_9_11(conv_u2u_8_9(C_1_sva)
                + conv_u2u_8_9(D_1_sva)))));
            in_i_5_sva_1 = in_i_5_sva + 3'b1;
            if ( ~ (readslicef_3_1_2((({1'b1 , (in_i_5_sva_1[2:1])}) + 3'b1))) )
              disable out_4_inExit;
            in_i_5_sva = in_i_5_sva_1;
            Temp2_4_sva = Temp2_4_sva_1;
          end
        end
        begin : waitLoop8Exit
          forever begin : waitLoop8
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop8Exit;
          end
        end
        // C-Step 5 of Loop 'main'
        Temp2_5_sva = conv_u2u_128_64(Temp2_4_sva_1 * conv_u2u_16_64(out_1_mul_1_cse_sva));
        in_i_6_sva = 3'b0;
        begin : out_5_inExit
          forever begin : out_5_in
            // C-Step 0 of Loop 'out_5_in'
            begin : waitLoop9Exit
              forever begin : waitLoop9
                @(posedge clk);
                if ( rst )
                  disable mainExit;
                if ( clk )
                  disable waitLoop9Exit;
              end
            end
            // C-Step 1 of Loop 'out_5_in'
            Temp2_5_sva_1 = Temp2_5_sva + conv_u2u_9_64(readslicef_11_9_2((conv_u2u_10_11({(conv_u2u_8_9(A_1_sva)
                + conv_u2u_7_9(B_1_sva[7:1])) , (B_1_sva[0])}) + conv_u2u_9_11(conv_u2u_8_9(C_1_sva)
                + conv_u2u_8_9(D_1_sva)))));
            in_i_6_sva_1 = in_i_6_sva + 3'b1;
            if ( ~ (readslicef_3_1_2((({1'b1 , (in_i_6_sva_1[2:1])}) + 3'b1))) )
              disable out_5_inExit;
            in_i_6_sva = in_i_6_sva_1;
            Temp2_5_sva = Temp2_5_sva_1;
          end
        end
        begin : waitLoop10Exit
          forever begin : waitLoop10
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop10Exit;
          end
        end
        // C-Step 6 of Loop 'main'
        Temp2_6_sva = conv_u2u_128_64(Temp2_5_sva_1 * conv_u2u_16_64(out_1_mul_1_cse_sva));
        in_i_7_sva = 3'b0;
        begin : out_6_inExit
          forever begin : out_6_in
            // C-Step 0 of Loop 'out_6_in'
            begin : waitLoop11Exit
              forever begin : waitLoop11
                @(posedge clk);
                if ( rst )
                  disable mainExit;
                if ( clk )
                  disable waitLoop11Exit;
              end
            end
            // C-Step 1 of Loop 'out_6_in'
            Temp2_6_sva_1 = Temp2_6_sva + conv_u2u_9_64(readslicef_11_9_2((conv_u2u_10_11({(conv_u2u_8_9(A_1_sva)
                + conv_u2u_7_9(B_1_sva[7:1])) , (B_1_sva[0])}) + conv_u2u_9_11(conv_u2u_8_9(C_1_sva)
                + conv_u2u_8_9(D_1_sva)))));
            in_i_7_sva_1 = in_i_7_sva + 3'b1;
            if ( ~ (readslicef_3_1_2((({1'b1 , (in_i_7_sva_1[2:1])}) + 3'b1))) )
              disable out_6_inExit;
            in_i_7_sva = in_i_7_sva_1;
            Temp2_6_sva = Temp2_6_sva_1;
          end
        end
        begin : waitLoop12Exit
          forever begin : waitLoop12
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop12Exit;
          end
        end
        // C-Step 7 of Loop 'main'
        Temp2_7_sva = conv_u2u_128_64(Temp2_6_sva_1 * conv_u2u_16_64(out_1_mul_1_cse_sva));
        in_i_8_sva = 3'b0;
        begin : out_7_inExit
          forever begin : out_7_in
            // C-Step 0 of Loop 'out_7_in'
            begin : waitLoop13Exit
              forever begin : waitLoop13
                @(posedge clk);
                if ( rst )
                  disable mainExit;
                if ( clk )
                  disable waitLoop13Exit;
              end
            end
            // C-Step 1 of Loop 'out_7_in'
            Temp2_7_sva_1 = Temp2_7_sva + conv_u2u_9_64(readslicef_11_9_2((conv_u2u_10_11({(conv_u2u_8_9(A_1_sva)
                + conv_u2u_7_9(B_1_sva[7:1])) , (B_1_sva[0])}) + conv_u2u_9_11(conv_u2u_8_9(C_1_sva)
                + conv_u2u_8_9(D_1_sva)))));
            in_i_8_sva_1 = in_i_8_sva + 3'b1;
            if ( ~ (readslicef_3_1_2((({1'b1 , (in_i_8_sva_1[2:1])}) + 3'b1))) )
              disable out_7_inExit;
            in_i_8_sva = in_i_8_sva_1;
            Temp2_7_sva = Temp2_7_sva_1;
          end
        end
        begin : waitLoop14Exit
          forever begin : waitLoop14
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop14Exit;
          end
        end
        // C-Step 8 of Loop 'main'
        Temp2_8_sva = conv_u2u_128_64(Temp2_7_sva_1 * conv_u2u_16_64(out_1_mul_1_cse_sva));
        in_i_9_sva = 3'b0;
        begin : out_8_inExit
          forever begin : out_8_in
            // C-Step 0 of Loop 'out_8_in'
            begin : waitLoop15Exit
              forever begin : waitLoop15
                @(posedge clk);
                if ( rst )
                  disable mainExit;
                if ( clk )
                  disable waitLoop15Exit;
              end
            end
            // C-Step 1 of Loop 'out_8_in'
            Temp2_8_sva_1 = Temp2_8_sva + conv_u2u_9_64(readslicef_11_9_2((conv_u2u_10_11({(conv_u2u_8_9(A_1_sva)
                + conv_u2u_7_9(B_1_sva[7:1])) , (B_1_sva[0])}) + conv_u2u_9_11(conv_u2u_8_9(C_1_sva)
                + conv_u2u_8_9(D_1_sva)))));
            in_i_9_sva_1 = in_i_9_sva + 3'b1;
            if ( ~ (readslicef_3_1_2((({1'b1 , (in_i_9_sva_1[2:1])}) + 3'b1))) )
              disable out_8_inExit;
            in_i_9_sva = in_i_9_sva_1;
            Temp2_8_sva = Temp2_8_sva_1;
          end
        end
        begin : waitLoop16Exit
          forever begin : waitLoop16
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop16Exit;
          end
        end
        // C-Step 9 of Loop 'main'
        Temp2_9_sva = conv_u2u_128_64(Temp2_8_sva_1 * conv_u2u_16_64(out_1_mul_1_cse_sva));
        in_i_10_sva = 3'b0;
        begin : out_9_inExit
          forever begin : out_9_in
            // C-Step 0 of Loop 'out_9_in'
            begin : waitLoop17Exit
              forever begin : waitLoop17
                @(posedge clk);
                if ( rst )
                  disable mainExit;
                if ( clk )
                  disable waitLoop17Exit;
              end
            end
            // C-Step 1 of Loop 'out_9_in'
            Temp2_9_sva_1 = Temp2_9_sva + conv_u2u_9_64(readslicef_11_9_2((conv_u2u_10_11({(conv_u2u_8_9(A_1_sva)
                + conv_u2u_7_9(B_1_sva[7:1])) , (B_1_sva[0])}) + conv_u2u_9_11(conv_u2u_8_9(C_1_sva)
                + conv_u2u_8_9(D_1_sva)))));
            in_i_10_sva_1 = in_i_10_sva + 3'b1;
            if ( ~ (readslicef_3_1_2((({1'b1 , (in_i_10_sva_1[2:1])}) + 3'b1))) )
              disable out_9_inExit;
            in_i_10_sva = in_i_10_sva_1;
            Temp2_9_sva = Temp2_9_sva_1;
          end
        end
        begin : waitLoop18Exit
          forever begin : waitLoop18
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop18Exit;
          end
        end
        // C-Step 10 of Loop 'main'
        Temp2_10_sva = conv_u2u_128_64(Temp2_9_sva_1 * conv_u2u_16_64(out_1_mul_1_cse_sva));
        in_i_11_sva = 3'b0;
        begin : out_10_inExit
          forever begin : out_10_in
            // C-Step 0 of Loop 'out_10_in'
            begin : waitLoop19Exit
              forever begin : waitLoop19
                @(posedge clk);
                if ( rst )
                  disable mainExit;
                if ( clk )
                  disable waitLoop19Exit;
              end
            end
            // C-Step 1 of Loop 'out_10_in'
            Temp2_10_sva_1 = Temp2_10_sva + conv_u2u_9_64(readslicef_11_9_2((conv_u2u_10_11({(conv_u2u_8_9(A_1_sva)
                + conv_u2u_7_9(B_1_sva[7:1])) , (B_1_sva[0])}) + conv_u2u_9_11(conv_u2u_8_9(C_1_sva)
                + conv_u2u_8_9(D_1_sva)))));
            in_i_11_sva_1 = in_i_11_sva + 3'b1;
            if ( ~ (readslicef_3_1_2((({1'b1 , (in_i_11_sva_1[2:1])}) + 3'b1))) )
              disable out_10_inExit;
            in_i_11_sva = in_i_11_sva_1;
            Temp2_10_sva = Temp2_10_sva_1;
          end
        end
        in_i_1_sva = 3'b0;
        begin : waitLoop20Exit
          forever begin : waitLoop20
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop20Exit;
          end
        end
        // C-Step 11 of Loop 'main'
        Temp2_11_sva = conv_u2u_128_64(Temp2_10_sva_1 * conv_u2u_16_64(out_1_mul_1_cse_sva));
        begin : out_11_inExit
          forever begin : out_11_in
            // C-Step 0 of Loop 'out_11_in'
            begin : waitLoop21Exit
              forever begin : waitLoop21
                @(posedge clk);
                if ( rst )
                  disable mainExit;
                if ( clk )
                  disable waitLoop21Exit;
              end
            end
            // C-Step 1 of Loop 'out_11_in'
            Temp2_11_sva_1 = Temp2_11_sva + conv_u2u_9_64(readslicef_11_9_2((conv_u2u_10_11({(conv_u2u_8_9(A_1_sva)
                + conv_u2u_7_9(B_1_sva[7:1])) , (B_1_sva[0])}) + conv_u2u_9_11(conv_u2u_8_9(C_1_sva)
                + conv_u2u_8_9(D_1_sva)))));
            in_i_1_sva_1 = in_i_1_sva + 3'b1;
            if ( ~ (readslicef_3_1_2((({1'b1 , (in_i_1_sva_1[2:1])}) + 3'b1))) )
              disable out_11_inExit;
            in_i_1_sva = in_i_1_sva_1;
            Temp2_11_sva = Temp2_11_sva_1;
          end
        end
        begin : waitLoop22Exit
          forever begin : waitLoop22
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop22Exit;
          end
        end
        // C-Step 12 of Loop 'main'
        Temp_rsc_mgc_out_stdreg_d <= conv_u2u_128_64(Temp2_11_sva_1 * conv_u2u_16_64(out_1_mul_1_cse_sva));
        begin : waitLoop23Exit
          forever begin : waitLoop23
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop23Exit;
          end
        end
        // C-Step 13 of Loop 'main'
      end
    end
    in_i_1_sva_1 = 3'b0;
    Temp2_11_sva_1 = 64'b0;
    in_i_1_sva = 3'b0;
    Temp2_11_sva = 64'b0;
    in_i_11_sva_1 = 3'b0;
    Temp2_10_sva_1 = 64'b0;
    in_i_11_sva = 3'b0;
    Temp2_10_sva = 64'b0;
    in_i_10_sva_1 = 3'b0;
    Temp2_9_sva_1 = 64'b0;
    in_i_10_sva = 3'b0;
    Temp2_9_sva = 64'b0;
    in_i_9_sva_1 = 3'b0;
    Temp2_8_sva_1 = 64'b0;
    in_i_9_sva = 3'b0;
    Temp2_8_sva = 64'b0;
    in_i_8_sva_1 = 3'b0;
    Temp2_7_sva_1 = 64'b0;
    in_i_8_sva = 3'b0;
    Temp2_7_sva = 64'b0;
    in_i_7_sva_1 = 3'b0;
    Temp2_6_sva_1 = 64'b0;
    in_i_7_sva = 3'b0;
    Temp2_6_sva = 64'b0;
    in_i_6_sva_1 = 3'b0;
    Temp2_5_sva_1 = 64'b0;
    in_i_6_sva = 3'b0;
    Temp2_5_sva = 64'b0;
    in_i_5_sva_1 = 3'b0;
    Temp2_4_sva_1 = 64'b0;
    in_i_5_sva = 3'b0;
    Temp2_4_sva = 64'b0;
    in_i_4_sva_1 = 3'b0;
    Temp2_3_sva_1 = 64'b0;
    in_i_4_sva = 3'b0;
    Temp2_3_sva = 64'b0;
    in_i_3_sva_1 = 3'b0;
    Temp2_2_sva_1 = 64'b0;
    in_i_3_sva = 3'b0;
    Temp2_2_sva = 64'b0;
    out_1_mul_1_cse_sva = 16'b0;
    in_i_2_sva_1 = 3'b0;
    Temp2_1_sva_1 = 64'b0;
    in_i_2_sva = 3'b0;
    E_1_sva = 8'b0;
    D_1_sva = 8'b0;
    C_1_sva = 8'b0;
    B_1_sva = 8'b0;
    A_1_sva = 8'b0;
    Temp_rsc_mgc_out_stdreg_d <= 64'b0;
  end


  function [8:0] readslicef_11_9_2;
    input [10:0] vector;
    reg [10:0] tmp;
  begin
    tmp = vector >> 2;
    readslicef_11_9_2 = tmp[8:0];
  end
  endfunction


  function [0:0] readslicef_3_1_2;
    input [2:0] vector;
    reg [2:0] tmp;
  begin
    tmp = vector >> 2;
    readslicef_3_1_2 = tmp[0:0];
  end
  endfunction


  function  [63:0] conv_u2u_9_64 ;
    input [8:0]  vector ;
  begin
    conv_u2u_9_64 = {{55{1'b0}}, vector};
  end
  endfunction


  function  [10:0] conv_u2u_10_11 ;
    input [9:0]  vector ;
  begin
    conv_u2u_10_11 = {1'b0, vector};
  end
  endfunction


  function  [8:0] conv_u2u_8_9 ;
    input [7:0]  vector ;
  begin
    conv_u2u_8_9 = {1'b0, vector};
  end
  endfunction


  function  [8:0] conv_u2u_7_9 ;
    input [6:0]  vector ;
  begin
    conv_u2u_7_9 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [10:0] conv_u2u_9_11 ;
    input [8:0]  vector ;
  begin
    conv_u2u_9_11 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [15:0] conv_u2u_32_16 ;
    input [31:0]  vector ;
  begin
    conv_u2u_32_16 = vector[15:0];
  end
  endfunction


  function  [15:0] conv_u2u_8_16 ;
    input [7:0]  vector ;
  begin
    conv_u2u_8_16 = {{8{1'b0}}, vector};
  end
  endfunction


  function  [63:0] conv_u2u_128_64 ;
    input [127:0]  vector ;
  begin
    conv_u2u_128_64 = vector[63:0];
  end
  endfunction


  function  [63:0] conv_u2u_16_64 ;
    input [15:0]  vector ;
  begin
    conv_u2u_16_64 = {{48{1'b0}}, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    Adding
//  Generated from file(s):
//    2) $PROJECT_HOME/ESL.c
// ------------------------------------------------------------------


module Adding (
  A_rsc_z, B_rsc_z, C_rsc_z, D_rsc_z, E_rsc_z, Temp_rsc_z, clk, rst
);
  input [7:0] A_rsc_z;
  input [7:0] B_rsc_z;
  input [7:0] C_rsc_z;
  input [7:0] D_rsc_z;
  input [7:0] E_rsc_z;
  output [63:0] Temp_rsc_z;
  input clk;
  input rst;


  // Interconnect Declarations
  wire [7:0] A_rsc_mgc_in_wire_d;
  wire [7:0] B_rsc_mgc_in_wire_d;
  wire [7:0] C_rsc_mgc_in_wire_d;
  wire [7:0] D_rsc_mgc_in_wire_d;
  wire [7:0] E_rsc_mgc_in_wire_d;
  wire [63:0] Temp_rsc_mgc_out_stdreg_d;

  mgc_in_wire #(.rscid(1),
  .width(8)) A_rsc_mgc_in_wire (
      .d(A_rsc_mgc_in_wire_d),
      .z(A_rsc_z)
    );
  mgc_in_wire #(.rscid(2),
  .width(8)) B_rsc_mgc_in_wire (
      .d(B_rsc_mgc_in_wire_d),
      .z(B_rsc_z)
    );
  mgc_in_wire #(.rscid(3),
  .width(8)) C_rsc_mgc_in_wire (
      .d(C_rsc_mgc_in_wire_d),
      .z(C_rsc_z)
    );
  mgc_in_wire #(.rscid(4),
  .width(8)) D_rsc_mgc_in_wire (
      .d(D_rsc_mgc_in_wire_d),
      .z(D_rsc_z)
    );
  mgc_in_wire #(.rscid(5),
  .width(8)) E_rsc_mgc_in_wire (
      .d(E_rsc_mgc_in_wire_d),
      .z(E_rsc_z)
    );
  mgc_out_stdreg #(.rscid(6),
  .width(64)) Temp_rsc_mgc_out_stdreg (
      .d(Temp_rsc_mgc_out_stdreg_d),
      .z(Temp_rsc_z)
    );
  Adding_core Adding_core_inst (
      .clk(clk),
      .rst(rst),
      .A_rsc_mgc_in_wire_d(A_rsc_mgc_in_wire_d),
      .B_rsc_mgc_in_wire_d(B_rsc_mgc_in_wire_d),
      .C_rsc_mgc_in_wire_d(C_rsc_mgc_in_wire_d),
      .D_rsc_mgc_in_wire_d(D_rsc_mgc_in_wire_d),
      .E_rsc_mgc_in_wire_d(E_rsc_mgc_in_wire_d),
      .Temp_rsc_mgc_out_stdreg_d(Temp_rsc_mgc_out_stdreg_d)
    );
endmodule



