directive set /Convolotion/Convolotion:core/Convolotion:core:conc/for:for:for:for-1:acc#1 RESOURCE_NAME for:mgc_Altera-Cyclone-II-6_beh_psr.mgc_add(9,0,3,1,11)
directive set /Convolotion/Convolotion:core/Convolotion:core:conc/for:acc#1 RESOURCE_NAME for:mgc_Altera-Cyclone-II-6_beh_psr.mgc_add(9,0,3,1,11)
directive set /Convolotion/Convolotion:core/Convolotion:core:conc/for:for:for:for-3:else:mul#1 RESOURCE_NAME for:for:for:mgc_Altera-Cyclone-II-6_beh_psr.mgc_mul(5,0,8,0,12)
directive set /Convolotion/Convolotion:core/Convolotion:core:conc/for:for:for:for-2:else:mul#1 RESOURCE_NAME for:for:for:mgc_Altera-Cyclone-II-6_beh_psr.mgc_mul(5,0,8,0,12)
directive set /Convolotion/Convolotion:core/Convolotion:core:conc/for:for:for:for-1:else:mul#1 RESOURCE_NAME for:for:for:mgc_Altera-Cyclone-II-6_beh_psr.mgc_mul(5,0,8,0,12)
