directive set /Convolotion/Convolotion:core/WAIT_DP#1/for:for:for:for:acc#6 RESOURCE_NAME for:for:for:mgc_Altera-Cyclone-II-6_beh_psr.mgc_add(2,0,2,0,2)
directive set /Convolotion/Convolotion:core/WAIT_DP#1/for:for:for:acc#1 RESOURCE_NAME for:for:for:mgc_Altera-Cyclone-II-6_beh_psr.mgc_add(2,0,2,0,2)
directive set /Convolotion/Convolotion:core/WAIT_DP#1/for:for:for:for:acc RESOURCE_NAME for:for:for:mgc_Altera-Cyclone-II-6_beh_psr.mgc_add(2,0,1,0,2)
directive set /Convolotion/Convolotion:core/WAIT_DP#1/for:for:for:acc RESOURCE_NAME for:for:for:mgc_Altera-Cyclone-II-6_beh_psr.mgc_add(2,0,1,0,2)
directive set /Convolotion/Convolotion:core/WAIT_DP#1/for:for:for:for:acc#3 RESOURCE_NAME for:for:mgc_Altera-Cyclone-II-6_beh_psr.mgc_add(9,0,3,1,11)
directive set /Convolotion/Convolotion:core/WAIT_DP#1/for:for:acc#3 RESOURCE_NAME for:for:mgc_Altera-Cyclone-II-6_beh_psr.mgc_add(9,0,3,1,11)
directive set /Convolotion/Convolotion:core/WAIT_DP#1/for:for:for:for:acc#1 RESOURCE_NAME for:mgc_Altera-Cyclone-II-6_beh_psr.mgc_add(9,0,3,1,11)
directive set /Convolotion/Convolotion:core/WAIT_DP#1/for:acc#1 RESOURCE_NAME for:mgc_Altera-Cyclone-II-6_beh_psr.mgc_add(9,0,3,1,11)
