directive set /Convolotion/Convolotion:core/core/for:for:for:for:else:mux#1.itm REGISTER_NAME for:for:for:for:else.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:else:mux.itm REGISTER_NAME for:for:for:for:else.reg
directive set /Convolotion/Convolotion:core/core/Krow#1.sva REGISTER_NAME reg#1
directive set /Convolotion/Convolotion:core/core/Krow#2.sva REGISTER_NAME reg#1
directive set /Convolotion/Convolotion:core/core/Krow#3.sva REGISTER_NAME reg#1
directive set /Convolotion/Convolotion:core/core/Krow#3.sva#1 REGISTER_NAME reg#1
directive set /Convolotion/Convolotion:core/core/Krow#1.sva#1 REGISTER_NAME reg#1
directive set /Convolotion/Convolotion:core/core/Krow#2.sva#1 REGISTER_NAME reg#1
directive set /Convolotion/Convolotion:core/core/Result#1.sva REGISTER_NAME Result#1.sva.reg
directive set /Convolotion/Convolotion:core/core/Result#1.sva.dfm REGISTER_NAME Result#1.sva.reg
directive set /Convolotion/Convolotion:core/core/Result#1.sva.dfm.dfm REGISTER_NAME Result#1.sva.reg
directive set /Convolotion/Convolotion:core/core/Result.sg2.sva REGISTER_NAME Result.sg2.sva.reg
directive set /Convolotion/Convolotion:core/core/Result.sg2.sva.dfm REGISTER_NAME Result.sg2.sva.reg
directive set /Convolotion/Convolotion:core/core/Result.sg2.sva.dfm.dfm REGISTER_NAME Result.sg2.sva.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:lor#3.lpi#3.dfm.st REGISTER_NAME for:for:for:for.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:lor#4.lpi#3.dfm.st REGISTER_NAME for:for:for:for.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:lor.lpi#3.dfm.st REGISTER_NAME for:for:for:for.reg
directive set /Convolotion/Convolotion:core/core/Result.sg1.sva REGISTER_NAME Result.sg1.sva.reg
directive set /Convolotion/Convolotion:core/core/Result.sg1.sva.dfm REGISTER_NAME Result.sg1.sva.reg
directive set /Convolotion/Convolotion:core/core/Result.sg1.sva.dfm.dfm REGISTER_NAME Result.sg1.sva.reg
directive set /Convolotion/Convolotion:core/core/for:for:for-1:for:slc.itm REGISTER_NAME for:for.reg
directive set /Convolotion/Convolotion:core/core/for:for:for-2:for:slc.itm REGISTER_NAME for:for.reg
directive set /Convolotion/Convolotion:core/core/for:for:for-3:for:slc.itm REGISTER_NAME for:for.reg
