directive set /Convolotion/Convolotion:core/core/Dcolumn:slc(Dcolumn)#1.itm REGISTER_NAME Dcolumn:slc(Dcolumn)#1.reg
directive set /Convolotion/Convolotion:core/core/Dcolumn:slc(Dcolumn)#1.itm#1 REGISTER_NAME Dcolumn:slc(Dcolumn)#1.reg
directive set /Convolotion/Convolotion:core/core/Drow:slc(Drow)#1.itm REGISTER_NAME Drow:slc(Drow)#1.reg
directive set /Convolotion/Convolotion:core/core/Drow:slc(Drow)#1.itm#1 REGISTER_NAME Drow:slc(Drow)#1.reg
directive set /Convolotion/Convolotion:core/core/Drow:slc(Drow)#7.itm REGISTER_NAME Drow:slc(Drow)#7.reg
directive set /Convolotion/Convolotion:core/core/Drow:slc(Drow)#7.itm#1 REGISTER_NAME Drow:slc(Drow)#7.reg
directive set /Convolotion/Convolotion:core/core/exit:for:for#1.sva REGISTER_NAME exit:for:for#1.sva.reg
directive set /Convolotion/Convolotion:core/core/exit:for:for#1.sva.st#1 REGISTER_NAME exit:for:for#1.sva.reg
directive set /Convolotion/Convolotion:core/core/exit:for:for:for#1.sva REGISTER_NAME exit:for:for:for#1.sva.reg
directive set /Convolotion/Convolotion:core/core/exit:for:for:for#1.sva.st#1 REGISTER_NAME exit:for:for:for#1.sva.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:else:mux.itm REGISTER_NAME for:for:for:for:else:mux.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:else:mux.itm#1 REGISTER_NAME for:for:for:for:else:mux.reg
directive set /Convolotion/Convolotion:core/core/Result#1.lpi.dfm REGISTER_NAME Result#1.lpi.reg
directive set /Convolotion/Convolotion:core/core/Result#1.lpi.dfm#6 REGISTER_NAME Result#1.lpi.reg
directive set /Convolotion/Convolotion:core/core/Result.sg2.lpi.dfm REGISTER_NAME Result.sg2.lpi.reg
directive set /Convolotion/Convolotion:core/core/Result.sg2.lpi.dfm#6 REGISTER_NAME Result.sg2.lpi.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:lor.lpi.dfm REGISTER_NAME for:for:for:for:lor.lpi.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:lor.lpi.dfm#1 REGISTER_NAME for:for:for:for:lor.lpi.reg
directive set /Convolotion/Convolotion:core/core/Result.sg1.lpi.dfm REGISTER_NAME Result.sg1.lpi.reg
directive set /Convolotion/Convolotion:core/core/Result.sg1.lpi.dfm#6 REGISTER_NAME Result.sg1.lpi.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:else:mux#1.itm REGISTER_NAME for:for:for:for:else:mux#1.reg
directive set /Convolotion/Convolotion:core/core/for:for:for:for:else:mux#1.itm#1 REGISTER_NAME for:for:for:for:else:mux#1.reg
